CONTRIBUTING.md
SECURITY.md

Add CONTRIBUTING.md, SECURITY.md with basic instructions about contributing and reporting security issues.

Add minimal instructions about contributing and reporting security issues.

---

pkg/cri/resource-manager/policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go

- resource-manager: info-log post-policy container creation and update operations
- topology-aware: String()ify and debug-log hint scores.

fixes: log container creation and update operations, topology-aware hint scores.

---

pkg/cri/resource-manager/cache/utils.go

The naming of the cgroup directory varies depending on the cgroup driver
used by kubelet. Thus, the QoS class detection based on prefix matching
was not reliable. Change the detection to be more flexible, based on
substring matching.

resource-manager/cache: fix Pod QoS class detection

---

pkg/log/log.go

This patch
- adds support for multi-line logging
- precalculates and caches message prefix string, recalculates it only when necessary

pkg/log: support for multi-line logging, don't calculate message prefix all the time

---

pkg/agent/server.go

Create the directory for socket on agent startup. Use os.Remove() instead of syscall.Unlink() for removing lingering sockets.

fix: don't fail if socket directory does not exist on startup, create it instead.

---

pkg/cri/resource-manager/policy/policy.go
pkg/log/log.go

Propagate enabled policy debugging to the active backend's logger.

fixes: automatically enable debugging in the backend if it is enabled for 'policy'

---

.travis.yml
Makefile
elf/avx512.c
pkg/avx/collector.go

CI: build avx512 eBPF

---

pkg/cri/resource-manager/policy/builtin/topology-aware/cache.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

topologyaware: let formatter exploit fmt.Stringer interface implementations

---

CONTRIBUTING.md

Fix some minor typos in the CONTRIBUTING file.
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

CONTRIB: small typos

---

Makefile
test/functional/e2e_test.go
test/functional/fake_cri_server_test.go

This is preliminary e2e tests.
All test cases run in isolation: for each case a brand new resource manager is created and started together with a fake CRI gRPC server.
I'm going to simplify the code structure to make it more readable, hence WIP.

introduce end to end tests

---

pkg/agent/kubernetes.go
pkg/agent/watcher.go

Fix segfault when NODE_NAME is unset. Drop some commented out code

Agent fixes

---

pkg/cri/resource-manager/resource-manager.go
pkg/rdt/rdt.go

Fix segfault when NODE_NAME is unset. Drop some commented out code

rdt: extra hack for getting rdt properly configured and started

---

.circleci/config.yml

Demoed here:
https://app.circleci.com/github/marquiz/cri-resource-manager/pipelines?branch=devel%2Fcircleci
Runs tests in a container. CI takes about 1 minute from start to finish

Add support cor CircleCI

---

pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/sockets/sockets.go
test/functional/e2e_test.go

Try connecting by default to the containerd socket, both for the runtime and the image services.

resource-manager: default to connecting to containerd instead of dockershim.

---

pkg/rdt/config.go

Treat (absolute) l3 bitmasks of a class as if it is relative to the
"basemask" of its partition. This makes absolute bitmasks more usable in
the case of multiple partitions where the partition's basemask may
basically be semirandomly allocated anywhere in the available range of
bits.
An example: A partition has an l3 basemask 0xff0 and a class has an
absolute allocation schema 0x3. In this case the true allocated bitmask for
the class (resctrl group in the system level) would be 0x30.

rdt: make l3 bitmasks of classes relative to the partition

---

pkg/cgroups/cgroupstats.go
pkg/cgroupstats/collector.go
pkg/metrics/register/register_metrics.go

Add initial implementation of a cgroupfs based metrics collector, courtesy of Ismo.

[rebalancing] cgroupstats: add cgroupfs based metrics collector.

---

elf/avx512.c
pkg/avx/collector.go

Note: right now it's just a timestamp and missing how long ago it was
due to https://github.com/iovisor/gobpf/issues/213.

avx: track when avx512 activity was last recorded per cgroup

---

pkg/rdt/config.go

Make it possible to specify similar l3 cache configuration for
partitions as for classes. That is, we now allow both relative
(percentage) and absolute allocations (bitmask, bit numbers), and, also
make it possible to specify separate settings for CDP.
There are few restrictions, though. First, the same type of allocation
(relative/absolute) must be used between all partitions for certain cache id
(but different cache ids may incorporate different type of allocation).
E.g. cache id 0 might have percentage-based allocation whereas cache id
1 might have absolute bitmask-based allocation.
Second, if any partition has CDP (separate code and data) configuration
also all other partitions must have that specified. This is required
because allocations are exlusive and just using the "unified" …

rdt: allow more flexible l3 allocation of partitions

---

pkg/topology/topology.go

Moved part of the code from NewTopologyHints to getTopologyHint to
decrease cyclomatic complexity pointed out by gocyclo:
```
20 topology NewTopologyHints topology.go:80:1
```
This failure fails integration tests in intel-device-plugins-for-kubernetes. Here is a [correspondent PR](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/291/commits).

topology: decrease cyclomatic complexity

---

Makefile

Makefile: build without optimizations on "make DEBUG=1"

---

pkg/cri/resource-manager/policy/policy.go

Always sort data exposed/exported to containers by keys.

fixes: policy: sort exported container data by key.

---

cmd/cri-resmgr/main.go
pkg/cri/resource-manager/policy/flags.go

Add a command line flag, `--list-policies` for listing the available policies.

fixes: add a flag for listing available policies.

---

pkg/cpuallocator/allocator.go

It was mostly unused, anyway. Just use normal debug logging.

cpuallocator: drop '-cpu-allocator-debug' command line flag

---

pkg/sysfs/system.go

Do not attempt toggling CPUs online for the duration of system/topology discovery.
Notes: as a side-effect we don't have the correct topology info of offlined CPUs. They are correctly accounted to the physical package, but not to any NUMA node. Without further changes system/topology would need to be rediscovered if CPUs were dynamically onlined (which they are not ATM).

sysfs: don't try toggling CPUs online for the duration of system/topology discovery.

---

pkg/cri/resource-manager/events.go
pkg/cri/resource-manager/metrics/metrics.go
pkg/cri/resource-manager/policy/flags.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/requests.go
pkg/cri/server/server.go

This patch series pushes most of the logic for special treatment of the 'null' pseudo-policy to the policy layer itself.

fixes: push most of the handling of NullPolicy to the policy layer.

---

Makefile

On CircleCI we regularly run into the problem of some generated
protobuf code being out-of-date, although nobody has touched the
proto definitions. This is a workaround for that.

Makefile: don't insist on protoc, just give a warning if not found.

---

pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/utils.go

Memory requests cannot be estimated from the OOM-score adjustments with any acceptable accuracy, so stop trying it. For Guaranteed QoS class pods, use the memory limit as request and prefer using the CPU request as limit.

fixes/cache: stop trying to calculate memory requests

---

cmd/cri-resmgr-webhook/handlers.go

webhook: check for empty requests

---

pkg/cri/resource-manager/cache/cache.go

Spell out more explicitly the expected/preferred vs. rejected permission bits for the various cache/container data files and directories.Check that files and directories have root/root as owner/group. Violation of ownership or permission check of existing files/directories results in an error/rejection (and the failure of the related operation). Non-existent files/directories are created with the expected/preferred permissions (without an extra explicit check to see if we run as root/root).

cache: create directories/files with stricter permissions, check existing permissions.

---

pkg/agent/server.go
pkg/cri/resource-manager/sockets/sockets.go
pkg/cri/server/server.go

Don't overprotect socket directories so that group/world can't even try accessing sockets.

agent,server: allow access for everybody to socket directory.

---

sample-configs/blockio.cfg

blockio: update sample config to demonstrate annotations

---

.github/workflows/publish-docs.yml
.gitignore
Makefile
README.md
SECURITY.md
conf.py
demo/demos.rst
docs/blockio.md
docs/container-affinity.md
docs/html/index.html
docs/index.rst
docs/policy-memtier.md
docs/policy-static-pools.md
docs/policy-topology-aware.md
docs/rdt.md
docs/requirements.txt
index.rst
scripts/docs/make.bat
test/test.rst

Will need to add an ACCESS_TOKEN for deployment to GitHub pages.

Add Sphinx project for documentation publishing

---

pkg/cri/resource-manager/control/cri/cri.go

If we need to create an UpdateContainerResources request,
attach it to the container so the caller will know to send
it out on behalf of us.

fixes: control/cri: attach created update request to container.

---

pkg/avx/collector.go
pkg/cgroupstats/collector.go

Both AVX and cgroupstats Prometheus collectors report the cgroup
path differently. What's common is the container id.
Change the collectors to report cgroup_id which is the has value
used by container runtimes.

change avx and cgroupstats collectors to report container ID

---

demo/lib/host.bash
test/numa/run.sh

- verify creating Qemu opts successfully
- verify launching cri-resmgr successfully

e2e: add checks to test setup failures

---

Makefile
RELEASE.md

Describe the release process of cri-resource-manager.

Add RELEASE.md

---

test/e2e/run.sh

- cri-resmgr command line is extended with the parameters in the
cri_resmgr_extra_args.

e2e: add cri_resmgr_extra_args environment variable

---

pkg/agent/kubernetes.go
pkg/agent/watcher.go

- Change node name not set warning into error.

agent: refuse to start without NODE_NAME

---

docs/policy/rdt.md

Correct outdated information. Add more deetails.

docs: update RDT documentation

---

docs/conf.py

Only consider
- links or paths with a trailing .md as a markdown file, don't get fooled by something like foo.md.bar
- links or paths with a trailing .rst as a restructured text file, don't get fooled by something like foo.rst.bar
- a leading http:// or https:// as a remote reference/link

docs/conf.py: use more proper URI checks for testing links, .{md,rst}-files.

---

scripts/build/update-gh-pages.sh

So that it will be properly excluded from sphinx.

scripts: change docs build directory to _build

---

demo/lib/distro.bash

I used this to test different kernel versions on movable memory nodes when pinning container memory on those.
Do you think we could have this kind of helpers in our multi-distro support?

e2e: add ubuntu-download-kernel()

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new-release.md
docs/conf.py

Add issue templates for bug reports and feature requests. Change
RELEASE.md to an issue template.

github: add issue templates

---

test/e2e/run.sh

- py_consts contains user-defined Python code to be run before every
pyexec (that is, pp, verify, report etc.). User can define,
for instance, configurations like exclusive_cores={...}
and use those in verifications: 'cores["pod0c0"] in
exclusive_cores'.
- cri_resmgr_agent_extra_args variable is a place holder for passing
extra arguments to cri-resmgr-agent. This will be taken into use
in later patches that implement and refactor launcher code.
- Values of all test environment variables are stored under test
output directory for the record.

e2e: add and record environment variables in backend

---

test/e2e/run.sh

- extended-resources enables test code to add and remove extended
resources from the cluster.

e2e: add extended-resources to script API

---

pkg/cri/resource-manager/policy/builtin/memtier/dynamic_demotion.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go

The commit to disable the dynamic demoter by default accidentally put it on a permanent vacation. It is not configured correctly for the initial configuration (unless that has it disabled) and since it does not get properly reconfigured upon configuration changes, this prevents it from ever being activated. This patch should fix that.

memtier: properly reconfigure/start/stop dynamic demoter.

---

pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go

Deny empty config with zero pools.

static-pools: improved sanity check on pool configuration

---

.github/workflows/publish-docs.yml

https://github.com/softprops/turnstyle

github: use turnstyle for for serializing gh-pages updates

---

demo/lib/distro.bash

- Set proxies for pulling docker images and inside docker
containers.

e2e: preemptive proxy setup for containerd and docker

---

pkg/config/config.go

Unspecified values should be treated as defaults.

config: use defaults for unspecified values on config update

---

demo/lib/host.bash

Enables running E2E tests from different working directories and still
using the same, once downloaded VM image files.

e2e: store VM images and yamls under VM work dirs

---

test/e2e/run.sh

- Add cri-resmgr-webhook target to install (create yaml files and
keys), launch (kubectl apply yamls), terminate (kubectl delete yamls)
and uninstall (delete created yaml files).
- Add cri-resmgr-agent target to launch and terminate. Not added to
install: cri-resmgr-agent and cri-resmgr are installed together as
target "cri-resmgr".
- Launch cri-resmgr-agent at test startup by default.
- Add on_lauch hook.

e2e: install, launch, terminate and uninstall agent and webhook

---

demo/lib/vm.bash

(Fix a couple of shellcheck warnings in the vm library, too.)

e2e: add vm-install-cri-resmgr-webhook to the vm library

---

pkg/cri/resource-manager/policy/builtin/memtier/coldstart_test.go
pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go

This PR is on top of #510.
Rework the assignment of PMEM-only NUMA nodes to (one of) the closest DRAM node(s),
without the implicit assumption of the existence of a single unique closest DRAM node. The
updated assignment logic now assigns each CPU-less PMEM node to the closest CPU-ful
DRAM node with the fewest PMEM nodes already assigned. In case of a tie it chooses the
one with the lowest NUMA node ID.

memtier: rework PMEM-only NUMA node assignment.

---

pkg/cri/resource-manager/policy/builtin/memtier/coldstart_test.go

Stop hand-rolling the topology pools for tests assuming/hoping everything
will end up being as it would have been set up by `buildPoolsByTopology()`.
Instead, let `buildPoolsByTopology()` set up the pools based on the mocked
HW/system.

memtier: don't hand-roll pool topology for test.

---

test/e2e/policies.test-suite/memtier/c4pmem4/test01-pmem-node-assigning/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test02-annotation-memory-type/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test02-annotation-memory-type/memtype-guaranteed.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart/bb-coldstart.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/topology.var.json

The first e2e test for the memtier coldstart feature.
Depends on PR #506

e2e: memtier memory-type and coldstart tests

---

docs/policy/static-pools.md
pkg/cri/resource-manager/policy/builtin/static-pools/config.go
pkg/cri/resource-manager/policy/builtin/static-pools/flags.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
sample-configs/static-pools-policy.conf.example

Backport
- #476 
- #478 
- #513
In addtion, add a patch fixing dynamic configuration

release-0.4: static-pools policy fixes

---

test/e2e/run.sh

- Enables test code: namespace=kube-system create guaranteed

e2e: support namespaced kubectl create from templates

---

pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go

Run post-update hooks after successful change of configuration to enforce any policy
decisions made as a side-effect of the active adjusting itself to the new configuration.

resource-manager: run post-update hooks after reconfiguration.

---

test/e2e/run.sh

- The instantiate() function enables templating any file, for instance
cri-resmgr configuration.
- Templates use the same Bash syntax as create()'d yamls so far.

e2e: generalize templating any file with instantiate()

---

pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go

Don't leak a file descriptor for every file entry `uncompress()`ed from a testdata tarball.
Don't leak a file descriptor for every testdata tarball `uncompress()`ed. Also fix symlink
creation in `uncompress()` to work properly, instead of creating an empty file for each
symlink entry in the tarball.
Without this PR, adding more sample machine data causes a panic for any test that
tries to `uncompress()` the testdata tarball.

memtier/pool test: fix fd leakage causing test panics with more data.

---

pkg/cri/resource-manager/control/rdt/rdt.go

- `assignAll` is basically a controller-level (re-)configuration handler. Takes
care of re-assigning all containers as the set of available classes
might have changed and/or monitoring might have been enabled or
disabled.
- Only remove monitoring group of a container if it exist in a wrong class
(the container rdt class was changed) or if monitoring is set to
disabled. This way we don't unnecessarily reset the monitoring data and
history is preserved.

control/rdt: implement assignAll()

---

test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion/bb-memload.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion/cri-resmgr-dynamic-page-demotion.cfg

This tests dynamic demotion of heap with lots of small allocations.

e2e: test dynamic demotion

---

pkg/cri/resource-manager/control/rdt/rdt.go

Suppress warnings about missing classes for RDT default assignments in
Discovery mode if all of the Pod QoS class equivalents (BestEffort,
Burstable, Guaranteed) are missing from the configuration. That is, none
of the Pod QoS class equivalents are found pre-configured in the resctrl
filesystem.

rdt: accept missing default classes in Discovery mode

---

test/e2e/policies.test-suite/memtier/c4pmem4/test02-annotation-memory-type-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test02-annotation-memory-type-deprecated-syntax/memtype-guaranteed.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart-deprecated-syntax/bb-coldstart.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion-deprecated-syntax/bb-memload.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion-deprecated-syntax/cri-resmgr-dynamic-page-demotion.cfg

Update memtier E2E tests to use unified pod/container annotation syntax implemented in PR #588.

e2e: unified memory-type and cold-start annotation syntax

---

pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

Fall back to using normal CPUs if we have insufficient
reserved CPU capacity to allocate from. Give a warning
about potentially incorrect configuration whenever this
happens.

topology-aware: use normal as fallback for reserved.

---

test/e2e/policies.test-suite/topology-aware/n4c16/test05-reserved-resources/code.var.sh

Update E2E tests to match PR #622 reservation policy: when running out of reserved CPUs, fallback to using shared (instead of an error or overbooking reserved CPUs).
This updates tests to match "allocate always from root" that was introduced earlier (commit 086c30f5bd9e5d1bd2d393cd90723a7c063e98ae). Before that, kube-system pods could be pinned to a subset of reserved CPUs if reserved CPUs were spread across NUMA zones.

e2e: update tests on pinning reserved CPUs

---

pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

Moving up was limited to one level in the topology tree. In some cases
this is not sufficient to ensure the memory.

topology-aware: fix moving up memory grant

---

test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion/code.var.sh

This test was written with the assumption that every pod runs on its
own socket in the 4-socket system, and is pinned to the nearest DRAM
and PMEM memory. Now that socket #0 is reserved for kube-system and
will not run test workloads, one of the four workloads will be placed
on the root node. This increases the scope of this test, as we are
measuring demotion speed over many DRAM and PMEM nodes. This patch
updates the tests to correctly calculate total PMEM pages from many
PMEM nodes.

e2e: update dynamic page demotion tests

---

docs/demos/blockio.md
docs/developers-guide/architecture.md

blockio.md: added TM&B, revised sentence syntax

Basic edits to docs

---

demo/lib/distro.bash

e2e: switch k8s install source in opensuse

---

demo/lib/vm.bash

vm-install-dlv, vm-dlv-add-src and vm-dlv-update-config functions
enable conveniently adding go sources of many projects to vms.

e2e: add vm functions for dlv debugging

---

docs/developers-guide/e2e-test.md

Added trademark disclaimers for 3rd-party registered names.
Signed-off-by: Doug Martin <doug.martin@intel.com>

edited e2e-test.md

---

demo/lib/host.bash

Currently the test framework does not wait for `cloud-init` to finish when bootstrapping a VM. This can (and often does) break bootstrapping any distro that requires triggering a reboot from within `cloud-init`. One such distro is fedora, where we change cgroupfs mount options.
The breakage happens if
- `host-wait-vm-ssh-server` gets into the VM on the first boot after ssh has started but before `cloud-init` has rebooted, and
- the first subsequent `vm-command` runs after `cloud-init` has triggered a reboot but before the VM is up again
In such cases `vm-command` aborts with a (rather misleading) error about command failure. The fix is to wait for `cloud-init` to finish once the ssh server on the host is up.

e2e: wait for cloud-init to finish during VM bootstrap.

---

demo/lib/distro.bash

distro: update debian sid image URL.

0.6.0 release preparation: update sid image URL.

---

demo/lib/distro.bash

distro: centos-7 cluster bootstrapping fixes.

0.6.0 release preparation: centos-7 test cluster bootstrapping fixes.

---

Makefile
test/e2e/run.sh

e2e: use distro_binaries=1 for cross-built distro binaries.

0.6.0 release preparation: add support for testing with cross-built distro binaries.

---

test/e2e/policies.test-suite/topology-aware/c4pmem4/test03-coldstart-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/topology-aware/c4pmem4/test03-coldstart/code.var.sh

- PMEM usage was read before it became visible in sysfs.
- Used PMEM is not necessarily reported as Active, it may be
Inactive too. Switched to MemUsed as the source of information.

e2e: more robust coldstart test

---

demo/lib/distro.bash

distro-install-kernel-dev installs sources and build tools for
distribution-specific kernels.

e2e: add distro-install-kernel-dev for distro=opensuse

---

demo/lib/distro.bash
test/e2e/run.sh

Update F33 to F35 when creating Fedora images for testing.

e2e: Add support for Fedora 35 images

---

test/e2e/run.sh

- pidof cri-resmgr does not work when cri-resmgr runs with custom
glibc versions.

e2e: detect cri-resmgr(-agent) with fuser/pidfile instead of pidof

---

CODEOWNERS

Update CODEOWNERS adding an entry for @jukkar.

CODEOWNERS: add @jukkar.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go

Both branches are the same so remove the if-check as it is not
needed here.

topology-aware: Remove duplicate branch

---

docs/releases/conf.py

Supplements 09cc1ee31db37f2f634f8a58d3f7b46704764b0f.

docs: use myst markdown parser for docs/releases too

---

docs/policy/rdt.md

(cherry picked from commit 02a79520594b77d85d9c96bf7d65a405839762d5)

[release-0.6] docs: document rdt related annotations

---

docs/policy/topology-aware.md
test/e2e/policies.test-suite/topology-aware/n4c16/test10-additional-reserved-namespaces/cri-resmgr-reserved-namespaces.cfg.in

Document how to use ReservedPoolNamespaces option.

topology-aware: Add ReservedPoolNamespaces documentation

---

dockerfiles/cross-build/Dockerfile.centos-7
dockerfiles/cross-build/Dockerfile.centos-8
dockerfiles/cross-build/Dockerfile.debian-10
dockerfiles/cross-build/Dockerfile.debian-sid
dockerfiles/cross-build/Dockerfile.fedora
dockerfiles/cross-build/Dockerfile.suse-15.1
dockerfiles/cross-build/Dockerfile.suse-15.2
dockerfiles/cross-build/Dockerfile.ubuntu-18.04
dockerfiles/cross-build/Dockerfile.ubuntu-20.04
dockerfiles/cross-build/Dockerfile.ubuntu-21.04

Update cross-build dockerfiles to use golang version 1.17.

cross-build: build using golang version 1.17.

---

pkg/cri/resource-manager/requests.go

Don't trigger rebalancing without a policy and crash as an
end result (in the generic policy.Rebalance()). One way to
trigger such a crash (sans this commit) is to run with the
agent enabled and some external adjustment CustomResources
in place while no/nil policy is active.
Put in similar protection against trying to deliver events
or running post-update hooks for an updated configuration
with nil policy.

crash fix: don't try to rebalance/deliver events/trigger post-update hooks with nil policy.

---

docs/policy/topology-aware.md
test/e2e/policies.test-suite/topology-aware/n4c16/test11-reserved-cpu-annotations/code.var.sh
test/e2e/policies.test-suite/topology-aware/n4c16/test11-reserved-cpu-annotations/cri-resmgr-reserved-annotations.cfg.in
test/e2e/policies.test-suite/topology-aware/n4c16/test11-reserved-cpu-annotations/reserved-annotated.yaml.in

Added documentation and e2e test.

Reserved pool annotations additions

---

pkg/sysfs/system.go

On some HW we've seen more free that total memory being reported.
This causes an unsigned integer underflow in the calculation of
the amount of memory being used, resulting in exorbitant amounts
being reported. As a workaround, we calculate the amount of used
memory ourselves, capping the free memory to the total available
at max. to avoid similar underflows.

sysfs: workaround for bogus NUMA meminfo entry.

---

Makefile

Pull/refresh cross-build source images before cross-building.

build: pull/refresh cross-build source image.

---

Makefile

Add targets for building static binaries and cleaning up built binaries. Change `binary-dist` to build tarball from static binaries.

build: build binary tarball from static binaries.

---

docs/policy/balloons.md

- Describe how the policy works.
- Document relevant configuration parameters.
- Add CPU classes.

docs: improve balloons documentation

---

demo/lib/host.bash

`host-mount-vm` uses sshfs to mount test vm file system with root access under `~/vms/data/VMNAME/sshfs`. This enables using Your Favourite Editor as normal user on host for accessing files on the test vm, making testing and development more convenient.
The reason why I considered a separate helper function to be useful, instead of just using sshfs without helpers, is that the root access part is slightly tricky.

e2e: add host-mount-vm helper

---

sample-configs/balloons-policy.cfg

- Rename PreferSpreadingDifferentNamespaces to
PreferPerNamespaceBalloon.
- Add CPU class configuration section.

doc: update balloons sample configuration

---

demo/lib/vm.bash
test/e2e/policies.test-suite/topology-aware/n4c16/test09-container-exit/code.var.sh
test/e2e/run.sh

Small and minor tweaks to e2e tests. Noticed these when running e2e tests inside a VM.

Misc fixes to e2e tests

---

pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences.go
test/e2e/policies.test-suite/topology-aware/n4c16/test10-additional-reserved-namespaces/code.var.sh

**Notes:** This PR depends/is stacked on #936 which is stacked on #934. Please review / merge those ones first.
Adjust the handling of `prefer-reserved-cpus.cri-resource-manager.intel.com/[pod,$container]` annotations to allow explicitly annotated preferences to override namespace-based global preferences and opt the pod or the container out of the reserved pool.

topology-aware: allow annotated opt-out from reserved pool allocation.

---

docs/policy/balloons.md

This PR is part of the series that replaces PR #931.

doc: document AllocatorTopologyBalancing and ShareIdleCPUsInSame

---

.github/workflows/verify.yml
Makefile
cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile
go.mod
pkg/apis/resmgr/generated/clientset/versioned/fake/register.go
pkg/apis/resmgr/generated/clientset/versioned/scheme/register.go
pkg/avx/collector.go
pkg/blockio/blockio_test.go
pkg/cgroups/cgroupblkio.go
pkg/cpuallocator/allocator.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/log/log.go

[release-0.8] Bump builds to use Golang v1.19.6

---

docs/conf.py
docs/index.rst
docs/migration-to-NRI.md

Documentation for moving from CRI-RM to NRI.
Summary of changes:
- Added the docs/ directory
- Added migration-to-NRI.md with the steps

Migrating from CRI-RM to NRI

---

.github/workflows/common-build-docs.yaml
.github/workflows/common-codeql.yaml
.github/workflows/common-trivy.yaml
.github/workflows/verify.yml

github: use pinpointed ubuntu version on the runners

---

test/e2e/run.sh

If cri-resmgr changes CPU pinning at the same time when allowed resources of container's processes are read from /proc/PID/status, it may happen that different processes in the same cgroup show different CPU/memory masks. This patch fixes the race by retrying reading the resources few times. If the problem persists, it is most likely caused by multiple matching containers running in the vm, possibly created manually for debugging or by previously failed/aborted tests.

e2e: fix "ambiguous allowed resources" caused by race

---

pkg/cri/relay/relay.go
pkg/cri/relay/runtime-service.go
pkg/cri/server/services.go

This PR implements relaying the stream of events for CRI streaming GetContainerEvents() calls.

release-0.9: pkg/cri: implement container event relaying.

---

demo/lib/distro.bash

- distro's crictl is too old to support cri v1 -> install it from tarball
- vm-install-containernetworking failed so install cni-plugins directly from the distro.
- install container runtime(s) from the distro repo (as they're new enough there)
- remove failing snapd hack.

e2e: fixes for openSUSE

---

demo/lib/distro.bash
test/e2e/run.sh
test/e2e/run_all_configurations.sh

Drop support for EOL'd Fedora

---

demo/lib/distro.bash

They still need to use apt-key. Even if apt-key is deprecated we should be able to use it as long it exists on the host.

e2e: fix kubernetes repo key import for older ubuntu and debian

---

.github/ISSUE_TEMPLATE/new-release.md

Much of the stuff is now automated.

github: update the release process in the issue template
