pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/policy.go
pkg/sysfs/topology.go

Now cache.TopologyHints is a map, where key is a provider of the
hint. Providers can be kernel (sysfs), kubelet, etc...

Make TopologyHints to be more generic

---

pkg/agent/config-updater.go
pkg/agent/server.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/log/log.go

Remove Warning() from Logger interface as it was just replicating
(copy-paste) the Warn() function. Decreases LOC and increases
consistency as Warning() was only used in few places. Also, the logger
Backend interface does not have Warning().

log: drop Logger.Warning()

---

pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/container_test.go

For now we can ignore read-only mounts, as we don't expect them to be
very active. As well, ConfigMaps and Secrets that kubelet exposes to
containers can be skipped from hints generation.

Added support for more complex rules for mount topology hints

---

pkg/cri/resource-manager/builtin-policies.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/kubernetes/kubernetes.go
pkg/cri/resource-manager/policy/builtin/eda/eda.go

Implements a very simple (builtin) policy that simply looks at cpu.*
container annotations (ofthe CRI container object) in the
cri-resource-manager namespace (i.e.
cri-resource-manager.intel.com/cpu.*). If any annotations are found, the
cpusets within are combined and and the cpuset of the container is set
accordingly.

External Decision Agent (EDA) builtin policy

---

README.md
docs/policy-topology-aware.md
pkg/cri/resource-manager/builtin-policies.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/cache/utils.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/README.md
pkg/cri/resource-manager/policy/builtin/topology-aware/cache.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go
pkg/cri/resource-manager/policy/builtin/topology-aware/error.go
pkg/cri/resource-manager/policy/builtin/topology-aware/flags.go
pkg/cri/resource-manager/policy/builtin/topology-aware/hint.go
pkg/cri/resource-manager/policy/builtin/topology-aware/logging.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/instrumentation/flags.go
pkg/sysfs/idset.go
pkg/sysfs/parsers.go
pkg/sysfs/system.go
pkg/sysfs/topology.go
pkg/sysfs/utils.go
sample-configs/cri-resmgr-configmap.example.yaml

Add a new policy that splits the system up into a number of
hierarchically organised, partially overlapping pools (a tree),
based on hardware topology: full system / individual sockets /
NUMA nodes, CPUs/cores.
Containers are allocated resources from the best fitting pool.
The 'best fitting' pool is selected by calculating a score for
each available pool, taking into account container resource
requests, devices (including ones deduced from mounts), etc.
The scoring algorithm is not quite what it should be, it only
takes CPU into account ATM, is probably incomplete at best and
outright broken at worst. Work in progress...
The other preparing patches in this series add functionality required
by the topology-aware policy to sysfs and the cache, and fix a few
minor related bugs.

topology-aware-policy: add initial/prototype version.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/hint.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Add code to expose the allocated CPUs to containers similarly to the `static-plus` policy.
Container resource allocation (currently CPU only) is exposed using a container-specific directory wich is bind-mounted to `/.cri-resmgr` inside the container. It is populated with a single entry, `resource.sh`, which is a shell-source-able file containing information about the various kinds of CPUs allocated to the container. The contents of this file can be used by `isolation-aware` and `multi-CPU exclusive` containers to further pin their corresponding `threads` to the exclusively allocated (isolated or other) CPUs using `sched_setaffinity`. This file can also be monitored with `inotify` to get notifications about possible changes in CPU assignments.
The other patch in this PR fixes a small …

topology-aware: expose allocated shared, exclusive and isolated CPUs to contianers

---

Makefile
cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-agent/agent-deployment.yaml
cmd/cri-resmgr/cri-resource-manager.service
cmd/cri-resmgr/cri-resource-manager.sysconf
cmd/cri-resmgr/main.go
cmd/webhook/Dockerfile
packaging/rpm/cri-resource-manager.spec.in
pkg/cri/relay/relay.go
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/sockets/sockets.go
pkg/version/version.go
scripts/build/docker-build
scripts/build/git-id

This patch set
- cleans up (rather heavy-handedly) our Makefile, keeping it mostly target-compatible  
- adds a Makefile `install` and `dist` targets
- adds helper package and Makefile glue for collecting version/build info in the binaries
- adds sample/very simple `RPM` packaging
- adds deployment YAML and `Dockerfile` w/ClearLinux for cri-resmgr-agent
- switches webhook's `Dockerfile` to use ClearLinux
- switches to more consistent socket naming
- adds dedicated socket directory for safer mounting into agent container
The version information can be queried with the new `--version` command line option. 
The printing function is really dumb, directly dumping raw data. For the version data this could be easily improved, for instance to separate any potential tag, additional number of …

build-system: clean up Makefile, add install and dist targets, autoversioning.

---

pkg/cri/resource-manager/policy.go
pkg/cri/resource-manager/policy/builtin/eda/eda.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go

Added `policy.Sync()` to the `Policy` and `Backend` interfaces.
`Sync()` is called with two slices of containers: those `added`
since the previous startup or sync, and those `deleted`.
This should enable policies to synchronize themselves much
more efficiently during startup. The active policy now gets
the target desired state atomically in a single go instead
of the old 'peephole' style of going through first a loop of
deleting stale containers followed by a loop of adding newly
discovered ones.
`Start()` has been extended in a logically identical manner.
It now gets called with the same extra arguments for initial
synchronization.
This patch also changes all policies to call internally `Sync()`
during `Start()` to do their initial synchronization. It also
adds default implementations of …

policy: add single-shot policy synchronization.

---

pkg/cri/server/server.go
scripts/testing/dockershim
scripts/testing/kubelet

- fix `kubelet` test wrapper script to reflect recent changes in default socket paths
- single out relevant command line options (cgroup driver, runtime endpoint, verbosity) and make them overridable with reasonable defaults
- fix cri/server to create its socket directory if necessary instead of failing to  start up

Fixes: update default socket path in scripts, create socket dir during startup.

---

pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/kubernetes/kubernetes.go
pkg/cri/resource-manager/policy.go
pkg/cri/resource-manager/policy/builtin/eda/eda.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/README.md
pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go
pkg/cri/resource-manager/policy/builtin/topology-aware/hint.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Using the new pod level affinity and anti-affinity annotations
one can assign signed weights to pairs of containers running on
the node.
This should allow policies to let users express soft 'pull' and
'push' preferences between containers. Containers that pull each
other should be put close together and containers that push each
other should be put apart from each other wrt. HW-topology.
The topology-aware policy implements this semantics in its container
placement algorithm. Of course, policies are free to define/use any
other semantics for affinity as they see fit.
Here is an example of an annotation which defines an affinity
from container4 to container1 and 3, and anti-affinity to
container2.
metadata:
name: "test-affinity"
annotations:
cri-resource-manager.intel.com/affinity: | …

Add intra-pod container affinity/anti-affinity support.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go

Don't just log about memory pinning, pin it for real.

topology-aware: fix omitted memory pinning.

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/policy.go

Update the state of a container to 'running' if/when it has been successfully started.

fixes: update state of started container

---

pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go

- don't assign the cpuset of the shared pool for containers that don't want/need it.
- fix sliced-off exclusive CPUs not getting properly assigned to containers
- let pods opt-out from allocating isolated CPUs to their containers
- unify the format of .cri-resmgr/resources.sh between static, static-plus and topology-aware policies
- unify isolation opt-out annotation between static and topology-aware policies.

fixes: fixes for static-plus policy CPU assignment, unify policy annotations and data exposed to containers

---

docs/rdt.md
pkg/cri/resource-manager/config/config.go
pkg/cri/resource-manager/config/defaults.go
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/policy/builtin/eda/eda.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/resource-control/control.go
pkg/cri/resource-manager/resource-manager.go
pkg/rdt/bitmask.go
pkg/rdt/config.go
pkg/rdt/info.go
pkg/rdt/rdt.go
pkg/rdt/rdt_test.go
sample-configs/cri-resmgr-configmap.example.yaml

This patch implements RDT support. The resource manager now has a common
confugration of a set of RDT classes (or resctrl CTRL groups) which the
policies are able to assign containers to. This RDT configuration is
dynamically updatable via the resource manager node agent
(cri-resmgr-agent). Resource manager has a built-in default
configuration containing three classes corresponding to the Pod QOS
classes of Kubernetes. The set of classes can be freely specified in the
configuration, but, one must ensure that classes required by the active
policies have been defined, and, that the maxmimum number of classes
(CLOSes) supported by the hardware is not exceeded.
This patch integrates RDT support to the static policy. The policy
simply assigns each container to an RDT class corresponding its …

Implement RDT support

---

pkg/cri/resource-manager/config/defaults.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/rdt/config.go
pkg/rdt/rdt.go
pkg/utils/json.go
sample-configs/cri-resmgr-configmap.example.yaml

Adds a new 'options' section into the RDT configuration, targeted for
common RDT-related config options. Under 'options', the patch specifies
two sub-sections 'l3' and 'mb' which both have one boolean setting, i.e.
'optional'. This can be used to specify that the corresponding schema in
the group configurations is optional, i.e. it is simply ignored if not
supported by the system. This setting defaults to false which results in
an error in case the schema (L3 or MB) is specified in the group
configuration but the technology (L3 or MB allocation) is not available
in the underlying system.

rdt: make it possible to specify L3 and/or MB optional

---

pkg/cri/resource-manager/policy/builtin/static/flags.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
sample-configs/cri-resmgr-configmap.example.yaml

Add a policy-level configuration setting for controlling RDT support.
The setting is tri-state:
- "off" disables RDT control from the policy
- "on" requires RDT support (error is returned if RDT is not
enabled/available on lower layers)
- any other value means autodiscovery, i.e. RDT control is enabled if
it's available
The setting defaults to 'auto'.

static policy: add config setting for enabling/disabling RDT

---

pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go

Integrate RDT support to the static-plus policy. Implementation
replicates static policy, that is, the container is assigned to an RDT
class that corresponds its Pod QOS class ('Burstable', 'BestEffort' or
'Guaranteed').

static-plus policy: support RDT

---

pkg/rdt/bitmask.go
pkg/rdt/config.go
pkg/rdt/info.go
pkg/rdt/rdt.go
sample-configs/cri-resmgr-configmap.example.yaml

Support L3 CDP, that is separate settings for L3 code and data paths.
The logic is such that if the configuration contains separate L3 code
and/or L3 data path setting we require that this is also supported by
the system - unless the corresponding 'optional' option(s) in the RDT
configuration has been set to true. The "unified" L3 schema is used as
a fallback value in case CDP is enabled in the system, but, either one
or both of the separate code/data settings is missing.

rdt: support L3 CDP

---

pkg/sysfs/topology_test.go

Without this patch topology tests fail if the repository happens to be cloned to/from s directory where $(pwd) contains any symlinks. Resolve symlinks in mockRoot to avoid this.

sysfs: fix topology unit tests for mockRoot vs. symlinks.

---

pkg/rdt/rdt.go

In case a resctrl write operation fails read a more descriptive error message from info/last_cmd_status under the resctrl filesystem.
Also. contains a second patch that optimizes writes to the `tasks` file of resctrl groups.

rdt: more informative error messages

---

pkg/cri/resource-manager/cache/utils.go

When determining the Pod QOS class from the cgroup directory name.
Similar to what kubelet does.

resource-manager/cache: take Pod QOS class names from k8s api

---

pkg/agent/config-updater.go
pkg/agent/flags.go
pkg/agent/kubernetes.go
pkg/agent/watcher.go
pkg/cri/resource-manager/config/api/v1/api.pb.go
pkg/cri/resource-manager/config/api/v1/api.proto
pkg/cri/resource-manager/config/server.go

This PR is stacked on (includes) PR #54 .
Return configuration update errors as a field in the reply message.
This allows the agent to differentiate between errors in delivery
vs. errors in applying an update.
For delivery errors the agent will keep retrying indefinitely, sending
an update request at periodic intervals. For errors in applying an
update the agent will give up immediately and only try sending a new
update when the configration is updated the next time.

config: return errors related to applying updates in the reply message

---

pkg/agent/config-updater.go
pkg/agent/flags.go
pkg/agent/kubernetes.go
pkg/agent/watcher.go
pkg/cri/resource-manager/config/server.go

This PR is stacked on (includes) PR #53 
Since gRPC servers tend to spawn a separate goroutine for each request, make as sure as humanly possible (without adding sequence numbers to the requests) that we process configuration updates sequentially by locking the server for the (initial) processing of every request.

resource-manager/config: make sure we don't process configuration update requests in parallel.

---

pkg/agent/flags.go
pkg/agent/kubernetes.go
pkg/agent/watcher.go

Move the logic for picking configuration data for the node
to the agent. Three `ConfigMaps` are tracked in decreasing
order of preference:
1. node-specific: `cri-resmgr-config.node.<node-name>`
2. group-specific: `cri-resmgr-config.group.<group-name>`
3. default: `cri-resmgr-config.default`
If none of these yields any data the effective node configuration
is the empty fallback configuration.
A node can be assigned to a `configuration group` by setting the
`cri-resource-manager.intel.com/group` label on the node to the
name of the group. Another label can be selected for this by
specifying the `--label-name <label>` command line option.

agent: move node configuration selection to the agent side.

---

pkg/agent/config-updater.go
pkg/agent/flags.go
pkg/agent/kubernetes.go
pkg/agent/watcher.go

This PR is stacked on (includes) PR #52 .
Filter update storms by queuing them internally and passing forward after a short timeout.
Also always reply with success for configuration updates. The old behavior of replying with an error and then indefinitely trying to resubmit the exact same already rejected data does not make sense. We can start reporting configuration failures asynchronously once we figure out how and where to propagate the error back. In the stock agent case, it could be propagated back to the offending ConfigMap.

agent: rate-limit configuration update storms with a small lowpass filtering timeout.

---

cmd/cri-resmgr/cri-resource-manager.service
cmd/cri-resmgr/cri-resource-manager.sysconf

This patchset fixes two problems mostly related to packaging:
1. cri-resmgr systemd service does not agent (we don't even provide a service for it).
2. Don't expect in the environment file that systemd would do recursive substitutions.

packaging fixes: cri-resmgr systemd service doesn't require 'agent', shouldn't expect recursive substitutions from systemd.

---

pkg/cri/resource-manager/cache/pod.go

We might not have webhook annotations at all. So filter
containers primarily by PodID and only secondarily by
potentially annotated init- vs. normalness.

fixes: don't blindly assume an annotating webhook is in place.

---

scripts/build/git-id

Github uses lightweight tags for releases, so start accepting
those as well when git-describing HEAD for generating version
ids.

scripts: accept unannotated tags for versioning.

---

go.mod

Currently there was an extra space in go.mod file, this patch fixes this.
Signed-off: Syed Ahsan <syed.ahsan.shamim.zaidi@intel.com>
#69

Remove extra space from go.mod

---

go.mod
go.sum

From v1.13 on, go mod seems to prefer indirect dependencies in go.sum instead of go.mod. So let's have them there.

go.mod: don't include indirect dependencies in go.mod.

---

pkg/cri/resource-manager/resource-control/control.go
pkg/rdt/rdt.go

Fix an error when writing multiple pids to resctrl tasks file.
Ignore non-existent pids when updating tasks file

rdt: fix writing multiple pids to tasks file

---

pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/resource-manager.go

Use the initial configuration queried from cri-resmgr-agent. Also,
initialize RDT before parsing this configuration because the config
parsing currently needs RDT information that is made available at RDT
initialization time.

resource-manager: use initial config received from agent

---

pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences_test.go

The tests cover 100% of pod-preferences.go. Hopefully the input and expected output make sense as I didn't fully understand the code's purpose. E.g. what is `elevate` in function results?
Also please check if the names of the test cases reflect their meaning.

topologyaware: cover pod-preferences.go with unit tests

---

pkg/cgroups/cgroupid.go
pkg/utils/cgroups.go

Don't bail out from filepath.Walk if a cgroup directory gets deleted between discovery and processing. This happens when a cgroup gets deleted after the entry list of its parent directory has been read but before filepath.Walk gets around to recurse into the directory itself.

fixes: don't bail out if a cgroup directory gets deleted between discovery and processing.

---

cmd/cri-resmgr/main.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/policy.go
pkg/cri/resource-manager/policy/builtin/eda/eda.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/flags.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/resource-manager.go

This patch set changes the startup sequence to fetch the latest known configuration and apply it before starting any policy/request processing. This allows, in principle, the active policy to boot
directly into its latest up-to-date configuration.
Moreover, loading this initial configuration is attempted, in decreasing order of preference, from
- forced configuration (for development, disables updates),
- the agent,
- last up-to-date configuration stored in the cache,
- fallback configuration (also if cached one fails to apply)
The original active/saved policy check recently removed from the cache is
now attempted by the resource manager once the initial configuration is
loaded.
***Notes***: The extra squashme-commits take care of modifying the unit-tests and mocked interfaces according …

devel: apply initial configuration before startup.

---

Makefile
pkg/avx/collector.go
pkg/avx/register.go

It is normal for a *build system* to *not have* the AVX collector's ELF binary for eBPF filtering installed. Currently,
- a failure to load the ELF binary causes the AVX collector's constructor to fail,
- which in turn causes the metrics collector's constructor to bail out with an error,
- which then causes the resource manager's constructor to fail
This prevents even the trivial end-to-end tests from running.
As a workaround split out the code responsible for automatically registering the AVX collector to a file of its own with a compilation constraint on (the lack of) a tag. When running/building tests, set up the default build tags so that the AVX registration code does not get compiled into the test binaries.

avx: disable AVX collector for tests.

---

pkg/cgroups/cgroupid.go
pkg/metrics/metrics.go

Add a few missing docstrings for exported types, functions in pkg/cgroups and pkg/metrics.

Fix: add missing docstrings for exported symbols.

---

pkg/rdt/bitmask.go
pkg/rdt/config.go
pkg/rdt/info.go
pkg/rdt/rdt.go
sample-configs/cri-resmgr-configmap.example.yaml

This patch tries to simplify the configuration of the RDT L3 allocation
and aims to make it slightly more comprehensible and user friendly.
Instead of having independent configuration sections (l3Schema,
l3CodeSchema, l3DataSchema), we now have separate 'unified', 'code' and
'data' settings under the 'l3Schema' key. E.g.
```
resctrlGroups:
Guaranteed:
l3Schema:
all:
unified: 90%
code: 100%
data: 80%
```
Moreover, 'unified' must always be specified, and, 'code' and 'data' go
together so that none or both of them must be specified (only specifying
one of them creates an error). These requirements were added in order to
reduce the risk of accidental misconfiguration.
Also. the fallback/failure logic has been simplified. Now the
configuration only fails if 'l3Schema' is specified but L3 CAT …

rdt: simplify l3 configuration

---

pkg/cri/resource-manager/cache/pod.go

Fix pod.GetContainers() to never assume a container is an
InitContainer unless we know it for sure (IOW our webhook
has explicitly annotated it so).

fix: assume containers are *not* InitContainers.

---

pkg/cri/resource-manager/policy/builtin/eda/eda.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go

There are several policies interested in system topology. Instead of duplicating code to do system/topology discovery in each, policy discover it once in the agnostic policy layer and pass it to the backend creation function. Also, change the signature of policy.CreateFn to take all arguments as part of policy.BackendOptions.

policy: pass discovered system/topology to backend.

---

docs/rdt.md
pkg/cri/resource-manager/resource-manager.go
pkg/rdt/bitmask.go
pkg/rdt/config.go
pkg/rdt/info.go
pkg/rdt/rdt.go
sample-configs/cri-resmgr-configmap.example.yaml

This patch implements a higher-level "partition" hierarchy for RDT
classes that allows easier configuration of exclusive resource
allocation. The partition confiugration specifies a portion of the
resources that will be shared by the classes under it.
One conceptual principle is that the resource allocation between
partitions is exclusive (i.e. there are no shared resources between
partitions) when the resource itself allows/supports exclusive
allocation. In practice, when we now have two resources (cache lines and
memory bandwidth), cache allocations are exclusive (no overlap on the
cache lines between partitions), but memory bandwidth may be overlap
(i.e. all partitions may have 100% of bandwidth).
This patch also changes the previously used terminology a bit: we now
use the term …

rdt: implement "partitions"

---

pkg/dump/flags.go

Log the details of evaluating dumping verbosity only once per encountered method name.
This should make '--logger-debug all' much more usable again regardless if message dumping is enabled.

dump: don't be so chatty about verbosity evaluation when debugging.

---

pkg/rdt/config.go

Makes the configuration more user friendly. Now the user does not need
to specify L3 or MB allocation (on the partition level) if there is only
one partition.

rdt: 100% default allocation on partition level

---

pkg/cri/client/client.go

Debug() is off by default, so log with Info() if we're waiting for the CRI server to start.

fix: client: log with Info() if we need to wait for the server.

---

pkg/utils/cgroups.go

Don't assume just docker runtime when looking up processes for a cgroup.

fix: utils: teach GetProcessInContainer() about containerd and crio.

---

pkg/rdt/config.go
sample-configs/cri-resmgr-configmap.example.yaml

Allow the user to specify just one value in the simple case where no
separate CDP (code and data prioritization) configuration is wanted.
I.e. the user can simply specify something like this:
l3Schema:
all: 100%

rdt: simplify l3 schema configuration

---

go.sum
pkg/rdt/config.go
pkg/rdt/info.go
sample-configs/cri-resmgr-configmap.example.yaml

Changes the configuration so that the MB allocation (rdt partitions) and
MB schema (rdt classes) values are now a specified as a list instead of
a single value. Also, a unit is now required in order to determine what
the user intended (100% is quite different than 100MBps in modern
systems). The value to use is picked depending on the mode active on the
os level (whether -o mba_MBps mount option was used or not).
A missing value (of the correct unit) is treated as a configuration
error. This means that normally all mb schemas must have a percentage
value, and, if 'o -mba_MBps' mount option of the resctrl fileystem, all
mb schemas must have a MBps value.
A configuration example:
```
rdt:
partitions:
default:
mbAllocation:
all: [90% 9000MBps]
classes:
Burstable:
mbSchema:
all: [66%, …
```

rdt: support MBps mode of memory bandwidth allocation

---

pkg/rdt/config.go

Makes debug prints more readable.

rdt: add JSON marshaller for l3AbsoluteAllocation

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go

Add LookupContainerByCgroup(), a function for finding a container based on a cgroupfs path.
We need this for associating collected cgroupfs based metrics with actual running containers.

[rebalancing] cache: add cache function for looking up containers by cgroup path.

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go

Add functions for manipulating container tags, which are basically dynamic labels which exist only in the scope of the resource manager itself. We'll use tags to attach dynamically changing attributes to running containers based on the collected metrics data.

[rebalancing] cache: add cache functions for tagging containers.

---

docs/container-affinity.md
pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/policy/builtin/topology-aware/README.md
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go

Allow affinity expressions to reference any of the following metadata:
- name
- namespace
- QoS class
- labels
- tags
- any of the above (sans tags) of the containers parent pod
This mechanism enables the use more flexible and fine-grained affinities. For instance, once can now create an affinity with a scope of all containers of Guaranteed QoS class pods.

[rebalancing] cache: allow affinity expressions to reference other metadata than just labels

---

docs/container-affinity.md
pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/policy/builtin/topology-aware/README.md
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go

Add support for registering implicit affinities. An implicit affinity is defined by a container eligibility test function and an affinity expression. When affinities for a container are looked up by the cache, all those implicit affinities get included for which the eligibility function called with the Container returns true.
Implicit affinities can be used to inject policy-specific affinities to all or a selected subset of containers, for instance to inject automatic AVX512 affinities and anti-affinities to containers.

[rebalancing] cache: add support for implicit container affinities.

---

pkg/cri/resource-manager/policy/builtin/eda/eda.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go

Add a mechanism for optimizing resource allocation for the current set of running containers.
Rebalance() is the primary mechanism for rebalancing/optimizing the resource allocations for the current set of running containers. The resource manager will (eventually) trigger rebalancing periodically. It is up to the policy backend to decide what kind of rebalancing strategy it implements.
The current API presents no way for the upper layer to restrict which containers are in the scope of rebalancing. Regardless, implementations should honor the existing/implied QoS-semantics of pods/containers: containers in Guaranteed QoS pods are not to be disrupted/touched.

[rebalancing] policy: add Rebalance(), stub backend implementations.

---

docs/container-affinity.md
pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/policy/builtin/topology-aware/README.md
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

This patch series adds the policy-specific bits for the AVX512 POC mitigation.
In particular, it
- defines a dedicated `tag` for AVX512 usage
- declares `implicit affinities` for AVX512-tagged/untagged containers
With these patches in place every container
- *tagged* with AVX512 will get injected with an `affinity` on AVX512-tagged containers
- *NOT tagged* with AVX512 will get injected with an `anti-affinity` on AVX512-tagged containers
Once the missing patches land for the upper layers to 
- *tag/untag* containers based *AVX512 usage/metrics*, and
- periodically *trigger rebalancing*
the original POC functionality wrt. mitigation should be fully restored.

[rebalancing] topology-aware: auto-inject AVX512 affinity/anti-affinity annotations.

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go

Don't recalculate container.PrettyName. Calculate it once then cache internally.

cache: cache and reuse container.PrettyName().

---

pkg/rdt/rdt.go
sample-configs/cri-resmgr-configmap.example.yaml

Now the reserved class name 'SYSTEM_DEFAULT' can be used in our rdt
configuration to specify the allocation for the "root" resctrl group of
the system (located in the root of the resctrl mount point). CRI-RM does
not do any modifications to the root resctrl group if SYSTEM_DEFAULT
class is not specified in the config. Thus, the existing default
functionality does not change, but, this gives the user the possibility
to configure the root group using CRI-RM.

rdt: allow configuration of the root resctrl group

---

pkg/sysfs/testdata/go.mod

This is a fix to #152 as a less intrusive alternative to #154 .
```
The zip archive code used in the go toolchain can't handle files
with a colon (:) in their name, even if those files are not used
by the toolchain in any way.
As a workaround, we force such files to be excluded from the parent
module by dropping an empty go.mod file above their location in the
source tree.
Workaround spotted in https://github.com/golang/go/issues/26672.
```

pkg/sysfs: kludge to exclude test data from (zip archives in) go get.

---

pkg/cri/resource-manager/config/server.go
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go

Clean up the generic resource manager code slightly by
chopping up the setup/startup sequence to smaller, more
orthogonal pieces.

[rebalancing] resource-manager: chop/clean up {set,start}up sequence code.

---

pkg/avx/collector.go
pkg/cgroups/v2path.go
pkg/cri/resource-manager/events.go
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/metrics/avx.go
pkg/cri/resource-manager/metrics/metrics.go
pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go
pkg/metrics/metrics.go

Note: *this PR set requires (IOW includes) #156 .*
This patch set adds a new metrics collector subpackage to the top-level generic resource-manager and initial code to the resource manager itself to trigger periodic rebalancing of the allocated container resources.
The metrics collector subpackage periodically
- polls the low-level collectors to acquire up-to-date *raw data*,
- preprocesses the data to produce events for the resource manager, and
- delivers these events to the resource manager
The events produced are (supposed to be) more *domain-specific* and better suited for consumption by the resource manager than just the collected low-level raw metrics data.
The resource manager
- pulls events from the metrics collector
- periodically triggers rebalancing
This initial patch set only …

[rebalancing] resource-manager: add skeletal events- and metrics-based rebalancing

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/policy/builtin/topology-aware/flags.go
pkg/cri/resource-manager/policy/builtin/topology-aware/hint.go
pkg/cri/resource-manager/policy/builtin/topology-aware/hint_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/topology/go.mod
pkg/topology/topology.go
pkg/topology/topology_test.go

Fixed the following  warnings:
```
topology.go:41:6: type name will be used as topology.TopologyHint by other packages, and that stutters; consider calling this Hint
topology.go:49:6: type name will be used as topology.TopologyHints by other packages, and that stutters; consider calling this Hints
```

topology: Fix golint warnings

---

pkg/cri/resource-manager/requests.go

Fix crash in RebalanceContainers when m.policy is nil

---

Makefile
elf/avx512.c

- Prevent accidently including userspace headers (-nostdinc).
- Fix include order - #include <linux/types.h> included
`include/uapi/linux/types.h` when `include/linux/types.h`
was wanted.

avx: fix building avx512.o on Linux 5.5

---

pkg/cri/resource-manager/events.go

Ouch... Don't deadlock main event handler on first AVX event
on the processEvent() -> processAvx() -> resolveCgroupPath()
path.

fixes: resource-manager: don't deadlock event handler.

---

go.mod
go.sum
pkg/avx/collector.go
pkg/cgroupstats/collector.go
pkg/metrics/metrics.go

This patch set fixes the current metrics collectors to always *explicitly describe* the the *full set of metrics* they ever might collect.
The original implementation, using `prometheus.DescribeByCollect` can only be used by collectors that always produce data for the same set of metrics. Our collectors are not like that. The collected set typically changes *dynamically* depending on the *state of the system*. For instance, the AVX collector does not produce any data when there are no processes using any AVX512 instructions.
Effectively this meant that the system state during cri-resmgr startup (or actually the very first internal round of collection, triggered by `DescribeByCollect()` had to be such that the full set of metrics was produced. Otherwise, only the initial subset ever showed …

fixes: metrics: describe metrics explicitly without having to collect any data

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/config/server.go

Make sure during startup that we have directories to put the config server socket and the cache file in.
Fixes #181 .

fixes: make sure config socket and cache dirs exist

---

pkg/cri/resource-manager/metrics/prometheus.go

Debug-log instead of Info-logging the whereabouts of Prometheus proxying.

resource-manager: be less Info-chatty about proxying to Prometheus.

---

pkg/cri/server/server.go
pkg/utils/net.go

Try harder detecting and refuse to start up if our server socket is already in use by another running instance.
Fixes #178 .

fix: fail to start up if another instance is already running.

---

pkg/cpuallocator/allocator.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go
pkg/sysfs/system.go

Make the `sysfs` package use interfaces instead of plain objects so we can mock them in tests. Use `CPUPackage` (and corresponding type `cpuPackage struct`) because "package" is a reserved word in Go. Also add `DiscoverSystemAt()` method for testing with fake sysfs directory hierarchy.
Note: relates to PR https://github.com/intel/cri-resource-manager/pull/90.

system: change system structs to interfaces

---

pkg/sysfs/system.go

Without trying to deduct it from the list of thread siblings. This is
more straightforward, plus, the previous method gave incorrect result if
the first thread sibling (whose id corresponds the core id) is offlined.

pkg/sysfs: get cpu core id directly from kernel

---

pkg/cri/resource-manager/metrics/avx.go

The Pod CgroupParent is a filesystem-relative absolute path. IOW, it is a path relative to the cgroupfs root but with a "/" prepended. Therefore use similar paths in AVX metrics events. Otherwise resolving cgroups to containers fail.

fix: resource-manager: use pseudo-absolute cgroup path in AVX metrics events.

---

pkg/cpuallocator/allocator.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go
pkg/sysfs/system.go

This patch adds support for per core priority in the cpu allocator used
by static, static-plus and topology-aware built-in policies. At this
point there is only support for two stages of priority (low and high).
The new allocator heuristics added in this patch are straightforward:
depending on the caller's guidance, the allocator always simply prefers
or tries to avoid high-priority CPUs.
Detection of high priority CPUs is currently based on the base_frequency
attribute. If CPUs with different base frequencies are detected, all
higher frequency CPUs (higher than the lowest detected base frequency)
are flagged as high priority.

Rudimentary support for CPU prioritization

---

pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Remove `discoveredSystem` interface and use `sysfs.System` interface instead.

topology-aware: start using sysfs.System interface.

---

pkg/cpuallocator/allocator.go
pkg/cpuallocator/cpuallocator_test.go

Implement a dummy fallback allocation method (takeAny()) that works
without any sysfs topology information. Also, add basic unit tests for
the CPUAllocator.

cpuallocator: don't crash if sysfs discovery fails

---

.circleci/config.yml
.github/workflows/go.yml
.travis.yml

Since we'll try to automatically regenerate .pb.go files if the corresponding proto-definitions our newer, add rules to pull in protoc and gRPC plugin before we kick off a build.

ci-build: add rules to install protoc and gRPC plugin.

---

.circleci/config.yml
.github/workflows/go.yml
.travis.yml

Keeping the linting tools up-to-date, upgrade to fresh release
of golangci-lint.

Update golangci-lint to v1.23.8

---

pkg/cpuallocator/allocator.go
pkg/cpuallocator/cpuallocator_test.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cpu.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Make the CPU allocator an interface. One motivation of this change is to
get rid of the sysfs discovery in the cpuallocator package.

cpuallocator: re-factor code

---

pkg/cri/resource-manager/policy/builtin/static/static-policy.go

Stop allocating isolated cores if the user requests for exactly two
logical cpus. Instead, allocate ordinary cores similarly to other cases.
The removed implicit logic was very unintuitive, assuming the user to
know/understand the internals of cri-resmgr, plus, giving varying
results e.g. depending on whether hyper-threading was enabled or not.

static-policy: drop the implicit logic of allocating isolcpus

---

pkg/cri/resource-manager/control/rdt/rdt.go
pkg/rdt/config.go
pkg/rdt/info.go
pkg/rdt/rdt.go
pkg/rdt/rdt_test.go

The resctrl API is essentially a singleton on the system level, thus,
there should be no reason to have multiple RDT separate control
interfaces in CRI-RM, either. This drops the 'Control' interface and
replaces that with "singleton" functions.
Also, add minimal unit test for the public interface, testing that an
uninitialized rdt interface works as expected.

rdt: un-export Control interface

---

pkg/sysfs/system.go

A one-liner fix to omit annoying and useless discovery time warnings.

fix: don't print warnings about successful  CPU online status discovery.

---

pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/resource-manager.go

Add support for reloading forced configuration upon a signal for simplifying development and testing of configuration handling in sub-components. If forced configuration is in use, by default it can be reloaded using SIGHUP. Setting the reload signal name to empty disables this altogether.

resource-manager: reload forced configuration on SIGHUP.

---

Makefile

On systems where 'command' is only available as a shell built-in. Adding
the semicolon causes gmake to invoke a true shell environment and the
command succeeds. Without this fix protoc utility is not found correctly
and every invocation of 'make' causes annoying
"make: command: Command not found"
to be printed in the terminal.

Makefile: fix discovery of protoc command

---

pkg/cri/resource-manager/control/rdt/doc.go
pkg/cri/resource-manager/control/rdt/flags.go
pkg/cri/resource-manager/control/rdt/rdt.go
pkg/rdt/info.go
pkg/rdt/rdt.go

The option is rather useless because in practice we depend on
(auto-)detecting the resctrl mount (options and mount point), anyway,
for determining the mode (percentage or MBPs) of MB allocation.
Simplifies the code and hopefully reduces confusion of the end users.

rdt: drop 'resctrl-path' config option and cmdline flag

---

pkg/cpuallocator/allocator.go
pkg/utils/sort.go

Will be utilized later in pkg/rdt

pkg/utils: add helper for sorting a slice of uint64

---

pkg/rdt/config.go

Makes it easier to test when the schemata output is reproducible, i.e.
cache ids are in sorted order.

rdt: construct schemata deterministically

---

pkg/cri/resource-manager/control/rdt/flags.go

Accidentally left behind when removing the 'resctrl-path' option.

resource-manager/control/rdt: drop stale struct member

---

pkg/log/log.go

Without jumping through all the configuration related hoops in order to
change the logger state. Helps writing/analyzing unit tests by making it
easy to enable debug logging.

pkg/log: make EnableDebug() effective immediately

---

docs/blockio.md
go.mod
go.sum
pkg/blockio/blockio.go
pkg/blockio/blockio_test.go
pkg/blockio/config.go
pkg/cgroups/cgroupblkio.go
pkg/cgroups/cgroupblkio_test.go
pkg/cri/resource-manager/control/blockio/blockio.go
pkg/cri/resource-manager/control/blockio/flags.go
pkg/testutils/verify.go
sample-configs/blockio.cfg

- Assign cgroup blkio parameters to containers according to pod's
block I/O or QOS class.
- Support cgroup v1.
- Support static configuration: existing block devices are scanned
only on configNotify to keep pod launch overhead minimal.

Add initial version of the blockio control

---

pkg/blockio/blockio.go

If a block I/O devices supports only one scheduler (for instance a software raid or DM device), then the sysfs/.../queue/scheduler simply contains the name of the only supported scheduler without any brackets.

pkg/blockio: fix unit test for single-scheduler-device case.

---

Makefile

Pass the 'test' build tag to all tests. This can/will be used by some e2e test cases to expose extra interfaces/functionality for testing/verification.

Makefile: pass 'test' build tag to all tests.

---

Makefile

Add `race-test` target to run non-verbose tests with race detection enabled in
a single directory. Use as
```
make WHAT=dir/to/test race-test
```
If `WHAT` is ommitted `race-test` is identical to `test`.

Makefile: add race-test target for race detection in a single dir.

---

cmd/cri-resmgr/main.go
go.mod
pkg/config/log.go
pkg/dump/dump.go
pkg/log/backend.go
pkg/log/default.go
pkg/log/delay.go
pkg/log/doc.go
pkg/log/flags.go
pkg/log/log.go
pkg/log/log_test.go
pkg/log/logger.go
pkg/log/ratelimit.go
pkg/log/ratelimit_test.go
pkg/log/signal.go
pkg/utils/parse.go

This patch set reworks the pkg/log, the common logger implementation with the primary aim being
- to make the logger race-free/properly locked
- clean up the implementation
- add unit tests for logging
The set of fixes, changes and improvements are:
- logging now should be race-free and multiple goroutine-safe (sans bugs)
- filter early messages until/unless the daemon decides to start up, or there is an error
- support for toggling full debugging on/off using SIGUSR1
- format, serialize and emit messages from an asynchronous goroutine
- properly handle and format multi-line messages without dedicated multi-line function calls
- unit test

logging: fix logging races, rework/clean up logger.

---

pkg/log/backend.go
pkg/log/log_test.go

It was a criminally braindead idea of mine to format logged
messages asynchronously. We regularly log data which soon
gets modified afterwards. Logging such data asynchronously
creates a window for read/write, iterate/write and other
races. So format messages synchronously.
Also add two test cases for the fmt backend. One just fuzzes
with log messages from concurrent goroutines. The other is
a test case for the above mentioned race condition bug.

fix race in fmt backend

---

pkg/log/backend.go
pkg/log/log.go

This gift just keeps on giving...
This fix should stop reconfiguration from screwing up logging.

log: formatting and post-configuration fixes.

---

Makefile

We need to pass test build tag to *all* go test tools, including vet.

Makefile: pass test build tags to vet.

---

pkg/cri/server/server.go
pkg/dump/dump.go
pkg/dump/dump_test.go
pkg/dump/flags.go

There are a number of race conditions in pkg/dump. The most prominent one is related to concurrent message dumping and dynamic reconfiguration. This one is relatively easy to trigger on  a busy node. It also gets immediately triggered when one starts adding other than trivial end-to-end tests.
This PR reworks pkg/dump to fix these race conditions and a number of its other problems. In particular the PR
- reworks message dumping to be race-free
- preserves the order of messages
- simplifies configuration by dropping command line support
- adds unit tests

dump: fix dump/config race conditions, preserve message order, add unit tests

---

pkg/cri/resource-manager/no-test-api.go
pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go
pkg/cri/resource-manager/test-api.go
test/functional/e2e_test.go

Free any lingering old instance of a container before recreating it.
kubelet occasionally fails to properly free crashed containers
before attempting to recreate and restart them. Check for this
and internally release any such instance if found. Likewise, do
a similar cleanup when a pod is being recreated.
Fixes #146 .

resource-manager: free any lingering instance upon pod/container recreation. 

---

pkg/cri/resource-manager/cache/pod.go

Make sure the slices returned by pod.GetContainers() and pod.GetInitContainers() contain every container only once.

fix: cache: don't return duplicates by pod.Get[Init]Containers().

---

pkg/config/config.go

Make sure that 'owning' configuration notification callbacks (attached during module registration as a `config.WithNotify()` option passed to `config.Register()`), are always invoked *before* 'foreign' notification callbacks (attached using `config.AddNotify()`). This establishes a notification invocation order that is defined well enough to be relied on.
Without this patch, notification callbacks were internally stored and therefore invoked in the temporal order of registration. If a foreign callback was attached to a yet to be created module, then eventually the module's own configuration callback(s) ended up registered and called after any such foreign one.

config: always call registration-time notifiers first.

---

pkg/cpuallocator/allocator.go

Without this patch, it is possible to trick the CPU allocator to crash, with enough/the right CPUs offline, as it ends up trying to index the first element of an empty slice when looking for idle cores.

cpuallocator: don't crash/try ever to index into an empty slice.

---

pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go

This patch series
- fixes memory type subset check to use proper sub-masking instead of comparison
- fixes a few scoring bugs inherited from the original topology-aware policy code
- adds detailed logging of the score sorting/comparison algorithm
- adds logging of the pod's/container's memory type preferences

memtier: fix memory type checking, a few inherited scoring bugs. 

---

pkg/blockio/blockio.go
pkg/blockio/blockio_test.go
pkg/blockio/config.go
pkg/cgroups/cgroupblkio.go
pkg/cgroups/cgroupblkio_test.go
pkg/cri/resource-manager/control/blockio/blockio.go
pkg/cri/resource-manager/control/blockio/flags.go
sample-configs/blockio.cfg

- Add cgroups file-to-oci blockio conversion.
- Add cgroups configuration transformation from whatever existing one
to wanted configuration by adding/modifying/removing parameters.
- Hook resetting blockio parameters to CRI-RM launch and config change.
- Add unit tests.

blockio: apply new and updated configs to running containers

---

cmd/webhook/handlers.go

Do not attempt to UID from request if its deserialization failed.

webhook: fix segfault in handler

---

pkg/cri/resource-manager/policy/builtin/memtier/cache.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go

Fix issues with:
* memory accounting during container release (the memory is now marked freed to the correct type)
* choosing nodes for score calculation: the nodes were chosen from the list of all nodes (with wrong indexing) instead of filtered node list
* restoring both memory and cpu grants properly when loading the cached state
Also refactor code a bit to nicer functions and correct interfaces.

memtier: fix a number of bugs related to scoring, restoring saved state, and memory accounting.

---

pkg/cri/resource-manager/events.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/requests.go

Fixes a segfault caused by config updates where the configuration of the
policy layer and the policy instance get out-of-sync. This happens
because we do not currently handle run-time configuration updates of
the upper policy layer. If we start with an empty config, (i.e. null
policy) no policy backend gets initialized. But, after a config update
the active policy in the configuration might have changed to something
else. Now, Bypassed() returned false (because it was looking at the
config) but in reality we did not have any policy backend. This caused a
segfault at request processing as we tried to do policy decisions with a
nil backend.
Even for the future, when config updates are fixed/supported, it is
probably safest to get this information directly from the policy
instance, rather …

policy: make Bypassed() a member of the policy interface

---

cmd/cri-resmgr-webhook/webhook-deployment.yaml

Not needed. Points to incorrect port and we use the service, anyway.

webhook: drop containerPort from the sample deployment spec

---

pkg/cri/resource-manager/control/cri/cri.go

Sometimes create.Config.Linux can be nil. Revealed by critest when
running against memtier and topology-aware policies.

fix potential nil pointer dereference in CRI controller.

---

cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-agent/agent-deployment.yaml

Simple nc to check if the agent socket accepts connections.

agent: add simple liveness probe to the sample deployment

---

pkg/cri/resource-manager/policy/builtin/memtier/README.md
pkg/cri/resource-manager/policy/builtin/memtier/cache_test.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go
pkg/sysfs/system.go

Based on comment https://github.com/intel/cri-resource-manager/pull/264#commitcomment-38987172, it seems that it would be better to use HBM instead of HBMEM in memtier. Do a project-wide string replacement. This breaks HBM annotation API (memory type was `hbmem` but is now `hbm`).

Convert HBMEM -> HBM everywhere.

---

cmd/cri-resmgr-agent/main.go

Call log.Flush() once in the beginning of main() in order to disable log
buffering (and thus, get rid of delayed log messages). Also, instead of
explicitly getting the default logger instance, use convenience logging
functions of the log package in main().

agent: call log.Flush() to disable log buffering

---

pkg/blockio/blockio.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/introspect/introspect.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/policy.go

[Update: changed annotation syntax and this description accordingly.]
This PR implements #226 .
This patch set implements initializing the default RDT and Block I/O classes of containers during container creation/discovery. The classes are initialized to the first successfully found value from the following list:
- container-specific class annotation value
- pod-default class annotation value 
- pod QoS class value
The class annotations are a more consistent variant of [these kubernetes conventions](https://kubesec.io/basics/metadata-annotations-seccomp-security-alpha-kubernetes-io-pod/), using the `rdtclass` and `blockioclass` keys in the usual resource-manager-specific `.cri-resource-manager.intel.com` key 'namespace'. Hence, the full key syntaxes are:
- …

cache: set default RDT and Block I/O classes when injecting container into cache.

---

pkg/cri/resource-manager/cache/cache.go

Don't crash trying to deferred-close a file that failed to open.

cache: don't segfault if opening/creating container data file fails.

---

README.md
sample-configs/memtier-policy.cfg

Reorganise README.md, adding a quick start section to the beginning. Minor fixes to the most ancient/outdated pieces. Add referenced memtier policy sample configuration.

documentation: reorganise README.md, minor fixes.

---

pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/metrics/metrics.go

We don't have a real rebalancing algorithm. Before we do, it does not make too much sense to collect metrics. Hence disable it by default.

resource-manager: disable periodic metrics collection by default.

---

pkg/cri/resource-manager/events.go
pkg/cri/resource-manager/flags.go

We don't have a real rebalancing algorithm at the moment. Before we do, it does not make sense to periodically trigger rebalancing. Hence disable it by default.

resource-manager: disable periodic rebalancing by default.

---

pkg/instrumentation/flags.go
pkg/instrumentation/instrumentation_test.go

Since we don't collect metrics by default, these should be disabled as well.

instrumentation: disable Prometheus exporter, endpoint by default.

---

go.mod
go.sum
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/utils.go

Add test cases for making sure the estimates of CPU requests/limits worth of full CPUs are accurate. Such containers are treated specially by stock kubernetes/kubelet as the 'static' policy considers Guaranteed QoS class containers with such requests eligible for exclusive CPU allocation.
Also, since the relevant related constants and functions are now exported from kubelet, pull in those ones and use them instead of duplication, whenever this is possible.

fixes/cache: add test cases for making sure CPU estimates are properly rounded for full CPUs.

---

pkg/cri/resource-manager/events.go
pkg/cri/resource-manager/events/events.go
pkg/cri/resource-manager/metrics/avx.go
pkg/cri/resource-manager/metrics/metrics.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go

This patch set extends the current resource manager event functionality in preparation for the memtier policy coldstart feature. The patch set
- adds support for handling events in policies
- adds support for generating events in policies
- generates an event on successful container startup

devel: add support for policy events, add/generate container startup event.

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go

Fail gracefully instead of crashing if filtering out pools with insufficient memory results in an empty set.

memtier: don't crash if no suitable pools are found.

---

.circleci/config.yml
Makefile

If go test is given a bunch of module paths it tries to test all of those in parallel using one instance per module directory. In CircleCI this seems to easily cause the exhaustion of memory and the tests to get killed by a SIGKILL.
As a workaround run tests explicitly with the golang toolchain parallel flag `-p 1` in CircleCI.

build: explicitly serialize go tests in CircleCI.

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/policy/builtin/memtier/README.md
pkg/cri/resource-manager/policy/builtin/memtier/cache.go
pkg/cri/resource-manager/policy/builtin/memtier/cache_test.go
pkg/cri/resource-manager/policy/builtin/memtier/coldstart.go
pkg/cri/resource-manager/policy/builtin/memtier/coldstart_test.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go

Add "cold start" functionality to the `memtier` policy. When cold start is enabled and the workload is allocated to a topology node with both DRAM and PMEM memory, the initial memory controller is only the PMEM controller. DRAM controller is added to the workload only after the cold start timeout is done. The effect of this is that allocated large unused memory areas of memory don't need to be migrated to PMEM, because it was allocated there to begin with. Cold start is configured like this in the pod metadata:
```
metadata:
annotations:
cri-resource-manager.intel.com/memory-type: |
container1: dram,pmem
cri-resource-manager.intel.com/cold-start: |
container1: 
duration: 60s
```
In the above example, `container1` would be initially granted only PMEM memory controller, but after 60000 …

memtier: add cold start feature.

---

pkg/cri/resource-manager/resource-manager.go

With setups where there's no agent and force-config is used, there's
no need to setup gprc.Dial. That keeps reconnecting and writing errors
to the log output.

resmgr: don't call the agent when force-config flag is used

---

demo/blockio/run.sh
demo/lib/command.bash
demo/lib/host.bash
demo/lib/vm.bash
test/critest/README.md
test/critest/memtier-policy.cfg
test/critest/run.sh
test/critest/tsl

- critest validates CRI without full Kubernetes stack,
requires a container runtime with containernetworking.
- All cri-resmgr *.cfg files in tests/critest are tested
to produce the same result as critest without cri-resmgr.
- Refactor demo/lib to reuse procedures in tests.
- Harmonize usage of test/critest and demo/blockio run.sh.

tests: add critest for CRI validation, add blockio demo test mode

---

pkg/metrics/register/register_metrics.go
pkg/metrics/register/register_metrics_avx.go

Previously, noavx tag was only used to skip AVX-512 collector
registration during testing. A user may also want to build completely
without the avx package (and its dependencies).
We add more noavx tags to be able to make completely avx code free
build when using: make BUILD_TAGS="-tags noavx"

build: add noavx tags to build without AVX-512 BPF collector

---

pkg/cri/resource-manager/control/rdt/rdt.go
pkg/cri/resource-manager/policy/builtin/memtier/README.md
pkg/cri/resource-manager/policy/builtin/memtier/dynamic_demotion.go
pkg/cri/resource-manager/policy/builtin/memtier/dynamic_demotion_test.go
pkg/cri/resource-manager/policy/builtin/memtier/flags.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/syscall_linux.go
pkg/utils/cgroups.go

"Dynamic demotion" means that non-used pages are demoted from DRAM to PMEM (if possible). See issue https://github.com/intel/cri-resource-manager/issues/244 for better description of the feature and some discussion about the implementation.
The code could use some work still (there's a number of TODOs still), but I would like to have feedback regarding the overall design and especially the heuristics for page selection.

memtier: dynamic demotion support.

---

pkg/cgroups/cgroupstats.go

file is a full cgroup path so the trimming does not give the expected
result.
Fix the size parsing by first taking the base of the path and then
splitting hugetlb.<size>.bar.

cgroupstats: fix hugetlb size parsing

---

pkg/cri/resource-manager/cache/utils.go
pkg/cri/resource-manager/control/blockio/blockio.go
pkg/cri/resource-manager/control/rdt/rdt.go
pkg/rdt/config.go
pkg/rdt/rdt.go

When running without any `RDT` / `BlockIO` classes configured, do not consider failed assignments to `BestEffort`, `Burstable`, or `Guaranteed` an error. These are the default classes inherited from the container's `Pod QoS class`. Also, for both controllers give a warning the first time the controller realizes it is running without any classes configured.

fixes: don't consider assignment to a default class an error if no classes are defined. 

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/control/memory/memory.go
pkg/cri/resource-manager/controllers.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/utils/cgroups.go

This patch set implements limiting the amount of DRAM/top tier memory a container can use with memory tiering.
In particular, it adds
- support for per container DRAM limits,
- support for setting per container DRAM limits using annotations, and
- a controller for enforcing DRAM limits using the memory cgroup controller

resource-manager: implement support for limiting the amount of DRAM/top tier memory a container can use.

---

pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/pod.go

Limiting the range of externally provided weights helps
internally generated affinities assign weights to their
desired effect, without having to use the min or max of
the expressible integer range. 
Additionally, we now use an explicitly defined const to
spell out default weights.

cache: limit annotated affinity weights to [-1000,1000].

---

pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/utils/cgroups.go

If we had failed to discover pod cgroup parent dir and proper QoS class, re-trigger disovery of
both at suitable events (cache reload, successful pod container creation).

fixes: re-trigger pod cgroup parent dir and QoS class discovery, if necessary.

---

README.md
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/resource-manager.go

Add command line option `--reset-cached-config` to reset any configuration data stored in the cache.

resource-manager: add command line option for resetting cached configuration.

---

README.md
cmd/cri-resmgr/cri-resource-manager.sysconf
cmd/cri-resmgr/fallback.cfg.sample
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/resource-manager.go

Change the default configuration to allow switching policies by default.
Add a brief chapter to README.md describing the current state of switching policies.

fixes: allow policy switch by default.

---

pkg/cri/resource-manager/control/rdt/rdt.go

Fix a crash due to misplaced logging of monitor group deletion in the RDT controller. Should fix #346 .

rdt: fix crash/misplaced logging of deletion.

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go

Only skip updating the cpuset of those containers that run on a purely exclusive set of cpus.
This should fix BestEffort containers not getting properly updated after exclusive allocations.

memtier, topology-aware: fix post-alloc update of shared cpuset.

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go

Tested with `memtier`:
With this patch (and with PR #349 cherry-picked for testing, using `test/numa/run.sh`):
```
vm=c4m4x2 cleanup=0 numanodes='[{"cpu": 4, "mem": "4G", "nodes": 2}]' reinstall_cri_resmgr=1 binsrc=local cri_resmgr_cfg=cri-resmgr-memtier.cfg
code="create guaranteed; CPU=2 create guaranteed; CPU=3 create guaranteed; report cpus"
./run.sh test
...
Pod   Cpus_allowed_mask
pod0  0000001
pod1  0000110
pod2  1110000
```
Running against current master (that is, use binsrc=github):
```
vm=c4m4x2 cleanup=0 numanodes='[{"cpu": 4, "mem": "4G", "nodes": 2}]' reinstall_cri_resmgr=1 binsrc=github cri_resmgr_cfg=cri-resmgr-memtier.cfg
code="create guaranteed; CPU=2 create guaranteed; CPU=3 create guaranteed; report cpus"
./run.sh test
...
Pod   Cpus_allowed_mask
pod0  00001111
pod1 …
```

memtier, topology-aware: fix exclusive allocation of multiple CPUs

---

demo/blockio/run.sh
demo/lib/command.bash
demo/lib/host.bash
demo/lib/numajson2qemuopts.py
demo/lib/vm.bash
test/numa/README.md
test/numa/besteffort.yaml.in
test/numa/burstable.yaml.in
test/numa/cri-resmgr-memtier.cfg
test/numa/guaranteed.yaml.in
test/numa/run.sh

- numajson2qemuopts.py: convert NUMA node list (JSON)
with CPUs, memory and distance definitions to Qemu options.
- demo/lib: add host-create-vm support for pass-through Qemu options
and NUMA node list in JSON.
- test/numa: add a test/demo for CPU binding.
- Refactor common parts from new test and demo/blockio to demo/lib/vm.
- Implements infra described in Issue #123.
- Implements a part of Container Affinity E2E validation, Issue #319.

tests: add NUMA node testing infra and memtier CPU isolation test

---

demo/lib/numactlH2numajson.py
demo/lib/numajson2qemuopts.py

Add utility to help cloning NUMA node configuration from a virtual machine or a bare metal server to a virtual machine used in end-to-end tests.
Example:
```
somehost$ numactl -H | python3 numactlH2numajson.py > numanodes.json
devhost$ numanodes="$(cat numanodes.json)" vm=virtual-somehost ./run.sh interactive
...
Entering the interactive mode until "exit".
run.sh> vm-command "apt install numactl; numactl -H"
```
`numactl -H` prints the same, given that `devhost` has enough resources.

numactlH2numajson: convert numactl -H output to numanode JSON

---

test/numa/run.sh

Distance syntax is was changed to such that all top-level keys have
fixed names instead of "dist-group-SOURCEGROUP"-like names that were
allowed in the first version. The default numanodes value was not
updated at that point, which caused regression.

e2e: fix deprecated node distance syntax in numalist JSON.

---

demo/lib/numajson2qemuopts.py
test/numa/run.sh

- Fixes the problem of NUMA nodes distributed over many sockets.
- Change the default test setup more realistic: symmetric CPUs in both
sockets.
- Fix default distance bug in numanodes JSON.

e2e: add sockets=N option to Qemu, change default test setup

---

demo/lib/topology.py

- Print CPU package/die/node/core/thread topology tree.
- Print CPU topology with allowed matching processes.
- Support topology visualization from local and remote hosts.

e2e: add topology utility/library to visualize topology

---

pkg/rdt/prometheus.go

Fix a 'string of one rune vs. string of digits' conversion/cast
error, detected when compiling with go1.15 or later.

rdt: fix a go1.15 test/build error.

---

pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/sysfs/system.go

We can't allocate a container exclusively to PMEM in movable memory zones. In such a case forcibly disable
coldstart and forcibly add DRAM to the memory preferences of all containers.

fix: force coldstart off, disable PMEM-only allocations if we have PMEM in movable memory zones.

---

demo/lib/host.bash
test/numa/run.sh

This patch makes it easy to start debugging `cri-resmgr` with delve in a fresh VM. Command
```
./run.sh debug
```
Does the following:
- Install `delve` to a VM.
- Copy `cri-resource-manager` sources to the VM.
- Configure `delve` to find the sources on the VM.
- Print help to user how to attach debugger to the running `cri-resmgr` instance, or how to relaunch `cri-resmg` inside the debugger.

e2e: "test/numa/run.sh debug" sets up delve in VM

---

pkg/cri/resource-manager/policy/builtin/static-pools/config.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go

Advertise CPUs belonging to the 'shared' and 'infra' pools (if any) via CMK_CPUS_SHARED and CMK_CPUS_INFRA environment variables. Compatibility backport from CMK

static-pools: advertise cpus in the shared and infra pools

---

pkg/cri/resource-manager/policy/builtin/memtier/hint.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/sysfs/system.go

Add topology support for physical packages with multiple dies. On multi-die systems the topology tree will
have additional nodes/pools representing dies. On a multi-socket system with multiple dies per socket the
full topology hierarchy is `root->socket->die->NUMA node` with `SNC` enabled. Consequently, allocations
not fitting into a single NUMA node will spill to the parent die before the socket.

memtier: add multi-die topology support.

---

pkg/cri/resource-manager/kubernetes/cpuset.go
pkg/cri/resource-manager/kubernetes/cpuset_test.go
pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go

When dumping a node in the tree of pools, calculating free shared CPU considered only
containers directly assigned to the node. Fix this to also account for any other containers
assigned elsewhere in the subtree below the node.
Additionally, split printing memory maps into a function of its own, dump CPU resources
and memory maps in a more compact  form. Finally, provide a function for more compact
human-readable dumps of CPUSets, by combining ranges of CPUs also when the diff
between subsequent elements is other then 1. This can shorten CPUSets like
`0,2,4,6,8,10,12,14,16,18,20` to `0-20:2`.

memtier: produce more correct, easier to read node supply dumps

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/policy/builtin/memtier/README.md

cache: add support for opting out from topology hint generation.
Using the new 'topologyhints' resource manager annotation
key it is now possible to opt out from automatic topology
hint generation on a per pod or container basis.
Use this annotation to opt out a full pod:
annotations:
topologyhints.cri-resource-manager.intel.com/pod: "false"
Use this annotation to opt out container 'foo' in the pod:
annotations:
topologyhints.cri-resource-manager.intel.com/container.foo: "false"
Currently topology hint generation is enabled by default, so
using the annotation as opt in (setting it to "true") should
have no effect on the placement of containers of a pod. This
might change in the future however.

cache: add support for opting out from automatic topology hint generation.

---

demo/lib/topology.py

This patch enables watching how Mems_allowed nodes are aligned in the topology tree.
Example: suspicious behavior in a corner case where a pod requesting more memory than available in any node. 
```
$ topology=... ./run.sh interactive
run.sh> CPU=1 MEM=12G create guaranteed
...
apiVersion: v1
kind: Pod
metadata:
name: pod0
labels:
app: pod0
annotations:
cri-resource-manager.intel.com/prefer-isolated-cpus: 'true'
spec:
containers:
- image: busybox
command:
- sh
- -c
- echo pod0 $(sleep inf)
imagePullPolicy: IfNotPresent
name: busybox
resources:
requests:
cpu: 1
memory: '12G'
limits:
cpu: 1
memory: '12G'
terminationGracePeriodSeconds: 1
```
When printing resources allowed to pod0, it seems to be allowed to use only single 1G memory node:
```
package0 die0 node0 core0 thread0 cpu00
thread1 …
```

e2e: topology.py visualizes memory nodes and Mems_allowed

---

README.md
pkg/cri/resource-manager/resource-manager.go

Always setup connection to the node agent as it serves other functions
than just config handling. Formerly the agent connection was not
initialized if --force-config was used. This was problematic, as e.g.
static-pools policy requires services (other than config) from the agent
and refused to work when forced config was used.

resource-manager: always setup node agent connection

---

pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/affinity_test.go

For affinities given in the simple notation always
generate a symmetric set of affinity expressions. IOW,
for every affinity X: Y with weight W, make sure there
is an affinity Y: X with weight W. |W| is now implicitly
DefaultWeight.

cache: make simple affinities implicitly symmetric.

---

demo/lib/topology.py
test/numa/besteffort.yaml.in
test/numa/burstable.yaml.in
test/numa/guaranteed.yaml.in
test/numa/run.sh

- Change variables visible in test script functions "verify",
"report" and "pyexec". Details below.
- Add allowed_RESOURCE[POD] variables to enable verifications
like verify 'len(allowed_nodes["pod0"]) == 1'.
- Add \"allowed\" variable to contain topology tree with pods as leaf
nodes on branches they are allowed to use.
- "report allowed" prints full topology tree with pods allowed to
use the resources.
- Drop "cpus" variable showing CPU masks without topology. The same
information is now available through allowed_cpus[pod].

e2e: integrate resource allocations topology to test scripts

---

Makefile
cmd/cri-resmgr/cri-resource-manager.service.in
dockerfiles/cross-build/Dockerfile.centos-7
dockerfiles/cross-build/Dockerfile.centos-8
dockerfiles/cross-build/Dockerfile.fedora
dockerfiles/cross-build/Dockerfile.suse-15.1
dockerfiles/cross-build/Dockerfile.suse-15.2
dockerfiles/cross-build/Dockerfile.ubuntu-20.04
scripts/build/docker-build-image

- fix previous shellcheck 'fix' breaking scripts/build/docker-build-image
- fix broken fedora cross-builds
- reduce initial in-container dnf/yum/zypper operation cost by using a minimal viable package set
- retain `fallback.cfg.sample` sample config name when installing it to `/etc/cri-resmgr`
- use `/etc/default` for default options on deb-based distros and `/etc/sysconfig` only on rpm-based ones
- add the necessary collateral for Ubuntu-20.04 cross-builds
- add generic cross-build targets `cross-packages`, `cross-rpm`, and `cross-deb`

packaging: various packaging fixes

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go

memtier: take parent grants into account for allocatable shared calculation
memtier: propagate exclusive allocations to parent pools/nodes
memtier: bugfixes for slicing off shared CPUs, prevent full exhaustion of shared CPU subsets of pools

memtier: a bunch of resource allocation/accounting fixes.

---

demo/lib/vm.bash
test/e2e/run.sh

- launch is needed after vm-reboot, for instance after kernel command
line change.
- uninstall and install help resetting and switching cri-resmgr
version, for instance in interactive mode if running outdated version
of cri-resmgr.

e2e: add uninstall, install and launch to script API

---

test/e2e/policies/memtier/n4c16/test01-always-fits/code.var.sh

Currently memtier refuses to exhaust even idle shared CPU subsets of
a pool. Therefore such attempts will try to squeeze the container to
another pool at the same level or, if none found, push the container
one level up to the parent pool.

test/e2e: fix: can't exhaust shared subset of CPUs.

---

demo/lib/vm.bash

With USE_NET_BRIDGES=1 govm launches Qemu with bridge configuration
instead of the default macvlan. The bridge configuration works in
github actions, while the default does not.
USE_NET_BRIDGES must be 0 by default until govm PR https://github.com/govm-project/govm/pull/44 is merged.
(Update: it is merged. However, we should make sure that govm/govm:latest image gets updated too, because using USE_NET_BRIDGES=1 with an outdated image will refuse to launch Qemu from the image.)

e2e/demo: run.sh passes through USE_NET_BRIDGES to govm

---

demo/lib/topology.py
test/e2e/run.sh
test/e2e/run_tests.sh

This patch set contains the following fixes to the end-to-end test infra:
- fix a small typo in the usage/help message of `test/e2e/run_tests.sh`
- correctly pass the `test`, `topology` and `policy` `directories` to `run.sh` for template resolution
- print the resolved template path and any template shadowing `warnings` to `stderr`
- catch and give special treatment to python `KeyError` and `IndexError` `exceptions` during verification
- filter empty lines from evaluated YAML templates
- don't hardcode a max. test case limit of 9 pods with 4 containers each

test/e2e: a bunch of small fixes and improvements.

---

.github/workflows/publish-docs.yml
Makefile
docs/Dockerfile

Add makefile rules for building and serving the html documentation inside a
container.
- Running `make site-build` will build the html content unders docs.
- Running `make site-serve` builds the site content and serves it at
http://localhost:8081/
Also use containerized build in github workflows – use the same workflow as developers are likely to use. Verifies that
containerized build of documentation works.
Drops all other files than the generated documentation in `gh-pages` branch in order to make
sure that the documentation is self-contained and does not depend on the
source tree.
The updated workflow can be verified here:
https://marquiz.github.io/cri-resource-manager

Containerized build of documentation

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go
test/e2e/policies/memtier/n4c16/test00-basic-placement/code.var.sh

Do not compare negative isolated capacities. In particular,
never consider equal negative capacities a tie. Do the same
for negative shared capacity. It's only for code symmetry, the
existing filtering of pools with insufficient resources should
already protect us from ever hitting that problem.
Add a minimal test set for verifying basic `memtier` container
placement.

memtier: fix eligible but unsatisfied isolated allocation, add basic placement tests.

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go
test/e2e/policies/memtier/n4c16/test00-basic-placement/code.var.sh
test/e2e/policies/memtier/n4c16/test03-simple-affinity/code.var.sh
test/e2e/policies/memtier/n4c16/test03-simple-affinity/guaranteed+affinity.yaml.in

Notes:
- This PR has been updated by pre-merging pending PRs #406. That should be reviewed separately.
- The algorithm has been slightly updated to dilute node/pool scores along the path less aggressively.
Calculate affinity for every node n based on the raw
affinities of the nodes along the path from n to root
and all the sub-nodes in the tree rooted at n.

memtier: better affinity scoring

---

Makefile
docs/INSTALL.md
packaging/deb.in/rules

Use `$(DEFAULTDIR)` to correctly pick distro-specific location for defaults (`/etc/sysconfig` vs. `/etc/default`).
This should fill incorrect default location used and referenced in debian/ubuntu packages.

packaging: install sysconf collateral to $(DEFAULTDIR).

---

demo/lib/vm.bash
test/e2e/run.sh
test/e2e/run_tests.sh

- run_tests.sh looks for vm-files directories under policy,
topology and test directories and constructs vm_files
variable recursively.
- run.sh writes files in vm_files associative array to vm.
- Files are written to vm before running/restarting cri-resmgr.

e2e: write files under vm-files to vm

---

test/critest/run.sh

- Fix critest on memtier policy, broken due to bad topology.
- Align cleanup behavior after test with e2e tests.
- Fix shellcheck errors.

critest: fix memtier test and default cleanup

---

docs/webhook.md

If `mutating-webhook-config.yaml` is applied before `webhook-deployment.yaml`, creating and updating pods will fail. That includes creating the `cri-resmgr-webhook` pod behind the webhook service.

docs: apply the webhook only after the webhook service is available

---

docs/developers-guide/architecture.md

Make documentation buildable, again.

docs: fix internal refs in architecture.md

---

docs/Dockerfile

Add git so that we're able to detect the version in the container build.
And, something other than "failed to determine version from any source"
is shown in the upper left corner of the page.

docs: install git into the site builder container image

---

.github/workflows/publish-docs.yml
Makefile
docs/_templates/layout.html
docs/conf.py
scripts/build/get-buildid
scripts/build/update-gh-pages.sh

This PR implements a complete pipeline of versioned documentation:
- adds a helper script for updating the `gh-pages` branch
- customizes the sphinx theme to include a version menu
- integrates versioned documentation into github actions
The basic idea here is that documentation is built whenever `master` or any `release-*` branch is update. It builds documentation for the updated "version" only, i.e. we don't always rebuild all documentation. The reasoning behind is:
- Only maintain documentation per major release. Latest point release (e.g. `v0.x.(y+1)` should be compatible with the previous point release (`v0.x.y`), also documentation-wise. This is what many other projects do, too.
- Build on updates of release branch, not on tags in order to make it easier to maintain older …

Implement versioned documentation

---

.github/workflows/publish-docs.yml

No use for that as we now build the docs with the helper script.

github: drop site-build from publish-docs workflow

---

docs/_templates/layout.html
docs/conf.py
scripts/build/update-gh-pages.sh

Change the versions menu in the bottom of navbar to be dynamic,
generated with js. The parent directory of the site is supposed to have
'versions.js' containing a simple object (map) of name-uri pairs.

docs: implement dynamic versions menu

---

docs/conf.py
docs/setup.md

When referencing files in this repo, create links to our github repo
instead of making a local copy.
Also, fixes handling of file references. When running through missing
references, only ignore file references with an absolute path. These
will reference the repo root directory and will be turned later on to
references to GitHub, directly. Missing references with a relative path
raise an error (as they should because the file really is missing).
Fix the broken references in the documentation, too, so that the
documentation builds without errors.

docs: create file references to github repo

---

docs/_templates/layout.html
docs/conf.py
docs/releases/conf.py
docs/releases/index.md
scripts/build/update-gh-pages.sh

Use a separate 'releases' subdir for the documentation archive.
Builds on top of #440

docs: archive documentation for tagged releases.

---

demo/lib/distro.bash

https requests from kube-apiserver to webhook services will escape
from the node to https_proxy, resulting in x509 certificate error on
unknown authority, unless .svc is in no_proxy.

e2e: fix no_proxy to include .svc

---

demo/lib/distro.bash
demo/lib/host.bash

- Do not change VM proxies if proxy configuration is already
up-to-date. This removes unnecessary start-up commands when
connecting to an already running VM for the test.
- Print docker command for viewing VM console output at start-up.

e2e: start-up improvements in proxies and printing

---

pkg/config/duration.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/control/page-migrate/demoter.go
pkg/cri/resource-manager/control/page-migrate/demoter_test.go
pkg/cri/resource-manager/control/page-migrate/flags.go
pkg/cri/resource-manager/control/page-migrate/page-migrate.go
pkg/cri/resource-manager/control/page-migrate/page-mover.go
pkg/cri/resource-manager/controllers.go
pkg/cri/resource-manager/policy/builtin/memtier/dynamic_demotion.go
pkg/cri/resource-manager/policy/builtin/memtier/flags.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/requests.go

This patch series is the first step in generalizing and improving dynamic page demotion by
introducing a new `page-migration` controller and splitting out the core of the functionality
from the `memtier` policy to this new controller. With this patch series applied any policy
can activate page demotion for container by simply attaching demotion policy decisions to
the desired containers.
In particular, the patch series
- adds functions for getting/setting page-migration policy/preferences to cache.Container
- adds a new `page-migration` controller
- moves the core of the demotion functionality to the new controller
- only leaves demotion/migration policy decision making in `memtier`
- fixes `resource-manager` to execute controller post-stop hooks for deleted containers
The current …

memtier, controllers: split out dynamic page demotion into a controller.

---

test/e2e/run_tests.sh

- Test runner sources *.source.* libraries from the test directory
hierarchy before executing test code.
- Test runner supports appending values of certain variables instead
of replacing inherited variable values. Now appending is done
implicitly on variables that contain code: code and py_consts.

e2e: add inherited libraries, py_consts and many codes to runner

---

pkg/cri/resource-manager/policy/builtin/static-pools/flags.go
pkg/cri/resource-manager/policy/builtin/static-pools/node.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
sample-configs/cri-resmgr-configmap.example.yaml

Drop all command line flags specific to the static-pools policy. Add new
configuration options for legacy pool config filesystem paths.
After this patch all settings are taken from the configuration system,
making configuration simpler to maintain and understand.
Add examples of all config options to the sample configmap.

static-pools: drop all cmdline flags

---

pkg/cri/resource-manager/policy/builtin/static-pools/config.go
pkg/cri/resource-manager/policy/builtin/static-pools/flags.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
sample-configs/static-pools-policy.conf.example

When reading legacy config (dir or file) from the filesystem only change
the pools in the active configuration. Do not override other config
options which are specified via the dynamic configuration system.
Based on top of #475

static-pools: take only pools from legacy config

---

test/e2e/run.sh

- cache.PolicyJSON.allocations is not available in static-pools
policy. Handle missing data gracefully when initializing variables
for pyexec/pp/verify/report.

e2e: fix static-pools cache in pyexec

---

demo/lib/vm.bash

Fixes regression caused by double-quoting `$append` in commit a60565a69b4a2e548198a699cdbe63bd069b6ab2.
This causes failing proxy env setup when setting up new VM.

e2e: fix vm-pipe-to-file

---

demo/lib/host.bash
test/e2e/run.sh

Benchmark results:
```
time distro=debian-sid code="exit 0" ./run_test.sh test
original: 5.8 s
fast ssh: 3.8 s
time distro=debian-sid code="vm-install-cri-resmgr-webhook" ./run_test.sh test
original: 23 s
fast ssh: 15 s
```
(The latter with PR #465 .)

e2e: faster ssh/scp by multiplexing socket

---

pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go

Change the handling of pools configuration.
First, respect the legacy config path (ConfDirPath, ConfFilePath)
specified in the dynamic configuration. If these settings change we
try to (re-)load the legacy config from the given location.
Second, the pools config priority should now be more consistent and
evident. The priority in descending order is:
1. dynamic configuration
2. leagcy config file
3. legacy config directory structure

static-pools: re-load legacy config on config update

---

pkg/cri/resource-manager/policy/builtin/static-pools/node.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go

Handle node update in a separate goroutine. With this patch node updates
no longer blocks policy startup and the node object gets updated when
agent connection becomes available.
In addition, node updates are now re-triggered on every configuration
update, making it possible to dynamically change node labeling/tainting
and the extended resources.
Based on top of #478

static-pools: lazier node updates

---

demo/lib/command.bash
demo/lib/host.bash
demo/lib/vm.bash

During the environment check, in addition to checking the mere existence of a stock SSH public key
- check if the corresponding private key is loaded to the agent,
- try loading it if it is not loaded yet,
- give up with an error message instructing the user what to do, if loading the key fails
Without this patch, if an encrypted/password-protected key is not loaded to the agent yet, the test
framework just sits in a loop forever, waiting for ssh'ing to the VM to eventually succeed, without
giving the user an indication about the real problem.

e2e,demo: check SSH key in/load SSH key to agent.

---

demo/lib/vm.bash

Only try to match the key fingerprint when checking if ssh key has been
loaded to ssh-agent.

demo/lib/vm.bash: fix ssh key matching

---

demo/lib/host.bash
test/e2e/run.sh

- Save static-over-boot information on VM to the data directory.
- Use saved information rather than defaults with an already
existing VM.

e2e: prevent trying to use a VM with wrong distro, user and cri

---

test/e2e/run.sh

Add `omit_agent` for allowing test cases to run without installing, setting up and launching `cri-resmgr-agent`. Defaults to `0`. Setting `omit_agent=1` omits the agent. Packaging tests are a prime example of when this makes a lot of sense.

fixes: allow test to omit installing/launching agent.

---

test/e2e/policies.test-suite/static-pools/README.txt
test/e2e/policies.test-suite/static-pools/cmk-exclusive.yaml.in
test/e2e/policies.test-suite/static-pools/cmk-isolate.yaml.in
test/e2e/policies.test-suite/static-pools/cmk-tolerating-guaranteed.yaml.in
test/e2e/policies.test-suite/static-pools/cri-resmgr.cfg
test/e2e/policies.test-suite/static-pools/distro.var
test/e2e/policies.test-suite/static-pools/n4c16/cri-resmgr-static-pools.cfg
test/e2e/policies.test-suite/static-pools/n4c16/py_consts.var.py
test/e2e/policies.test-suite/static-pools/n4c16/test00-node-status/code.var.sh
test/e2e/policies.test-suite/static-pools/n4c16/test01-exclusive-pods/code.var.sh
test/e2e/policies.test-suite/static-pools/n4c16/test02-pods-without-cmk/code.var.sh
test/e2e/policies.test-suite/static-pools/n4c16/test03-cmk-isolate/code.var.sh
test/e2e/policies.test-suite/static-pools/n4c16/test04-cmk-isolate-noaffinity/code.var.sh
test/e2e/policies.test-suite/static-pools/n4c16/test05-negative-tests/code.var.sh
test/e2e/policies.test-suite/static-pools/n4c16/topology.var.json
test/e2e/policies.test-suite/static-pools/n4c16/vm-files/etc/cmk/pools.conf
test/e2e/policies.test-suite/static-pools/static-pools-lib.source.sh

Opening the first static-pools tests patch for comments & discussion:
- What would be the minimum features that you'd like to see tested as part of this commit?
- Do you see major issues with the test structure? For instance, unlike in memtier tests, here cri-resmgr, agent and webhook are restarted before every test execution.

e2e: add tests for static-pools

---

dockerfiles/cross-build/Dockerfile.centos-7
dockerfiles/cross-build/Dockerfile.centos-8
dockerfiles/cross-build/Dockerfile.debian-10
dockerfiles/cross-build/Dockerfile.debian-sid
dockerfiles/cross-build/Dockerfile.fedora
dockerfiles/cross-build/Dockerfile.suse-15.1
dockerfiles/cross-build/Dockerfile.suse-15.2
dockerfiles/cross-build/Dockerfile.ubuntu-18.04
dockerfiles/cross-build/Dockerfile.ubuntu-20.04
scripts/build/docker-build-image

When building cross-build container images or cross-building packages
- don't ignore errors from useradd
- pass uid option to useradd without extra sed-trickery

cross-build: don't ignore useradd errors, pass options as such.

---

test/e2e/run.sh

Fixes help that should have been fixed when the topology-to-qemu-opts converter was renamed.

e2e: fix run.sh --help on topology

---

test/e2e/run_tests.sh

True editors like emacs may use these files for autosaves.

e2e: skip exporting variables from *#* files

---

test/e2e/run.sh

- Copy-pasting help on terminal provides quick access to values seen
in variables where assertion failed.

e2e: print post-mortem debugging help on assertion failure

---

demo/lib/topology.py

If there happened to be multiple podXcY's in cmdline, reporting resources allowed for the pid broke up. We're happy with just the first match.

e2e: fix handling many matching containers in topology reporting

---

test/e2e/run.sh

This enables test code like:
```
verify 'mems["pod0c0"] == {"node0", "node1"}'
```

e2e: enable verifying container memory pinning

---

test/e2e/run.sh

- vm=VM_NAME test/e2e/run.sh debug
fixed to work with vm's created with distro=debian-sid

e2e: fix setting up debug environment to debian-sid vm

---

test/e2e/run.sh

This helped catching cri-resmgr config errors that blocked launching it, as they did not appear as FATAL ERRORs in the output. The latter are already catched right above this addition in the code.

e2e: catch last cri-resmgr output line if process disappeared

---

pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go

If a cpuset is given among `AvailableResources`, use it as a bounding set during CPU resource discovery.

memtier: honor allowed CPUs in resource discovery.

---

pkg/cri/resource-manager/policy/builtin/memtier/resources.go

If a pod/container is annotated to opt out from isolated exclusive CPU allocation, or that is the configured memtier default and the pod/container is not annotated otherwise, honor this setting when allocating resources.

memtier: honor CPU isolation opt-out preference.

---

Makefile
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go

Get rid of the most of the cases where tests hand-rolled policy/pools instead of using the official policy 'constructor' for this.

memtier: get rid of hand-rolled policy/pools in most of the test cases.

---

pkg/cri/relay/runtime-service.go

Dump outbound (potentially altered) requests if debugging is enabled for the 'relay' source.

relay: dump outbound requests if debugging is enabled.

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go

Skip updating the container that triggered the change in
the shared subset of CPUs. Properly update the cpuset
of any affected container to the union of its exclusive and
shared CPUs.

memtier: fix updating containers after shared pool changes.

---

test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart/code.var.sh

Don't let previous cold start triggers in the log
fool us into thinking that the pending cold start
period would be over.

memtier/c4pmem4/test03-coldstart: don't jump the gun.

---

go.mod
go.sum

Avoid vendored-dist generating a *-dirty*-versioned tarball (`go mod vendor` effectively does `go mod tidy`).

go.mod, go.sum: update dependencies.

---

docs/_templates/layout.html

- remove 'v:' prefix from the version menu in order to avoid displaying
something like "v: v0.4.1"
- correct usage of `<dt>` tag

docs: minor fixes in html template customization

---

docs/_templates/layout.html
docs/conf.py
docs/releases/conf.py
scripts/build/update-gh-pages.sh

Change the versions menu so that the name of the current version shown matches one of the items of available versions. The detailed version number is still shown in the upper left corner of the page.
Based on #537

docs: use 'release branch' as the current version in versions menu

---

docs/_templates/layout.html
docs/conf.py
docs/releases/conf.py
scripts/build/update-gh-pages.sh

Two backports from master:
- minor fixes in html template customization (#537)
- use 'release branch' as the current version in versions menu (#538)

release 0.4: backport documentation theme fixes

---

test/functional/e2e_test.go

Prevent grpc from triggering read/write data race (concurrent klog flag.Set()
by our klogcontrol and klogging connection complaints by default grpc log)
by overriding the grpc logger.
Should fix the latest test failures in #546

test/functional: prevent read/write data race in klog.

---

scripts/hack/go-mod-replace-helper.sh

Help by printing out updated replace directives that can then be copied
to go.mod. An example for updating to k8s.io modules to v0.19.4:
$ sed -n '/replace/,$p' go.mod  | grep k8s.io | awk '{print $1}' | \
xargs ./scripts/hack/go-mod-replace-helper.sh ../k8s-cache/ v0.19.4
Note that the script does not do any dependency checking/tidying, but,
just blindly prints out revisions of whatever it is given.

scripts: helper for maintaining replace lines in go.mod

---

docs/policy/container-affinity.md

Unless properly quoted, sphinx passes '<' and '>' as such through to HTML output, rendering them and any text enclosed within `<>` invisible. Quote all text containing those within the affinity documentation using ``.

docs: quote text containing '<' and '>' using `` in affinity docs.

---

scripts/build/update-gh-pages.sh

Do not point to 'stable' version if that does not exist. Instead use the
current version.

scripts/update-gh-pages: more intelligent http redirect

---

demo/lib/vm.bash

- Enables running tests on real hardware servers instead of virtual machines.
- Example: VM_IP=servername VM_SSH_USER=username distro=distroname test/e2e/run.sh interactive

e2e: allow user override for VM_SSH_USER over distro-ssh-user

---

demo/lib/vm.bash

- Ease the pain of docker rate limit when needed container image is
among "docker images" on the host.
- Example: vm-put-docker-image busybox

e2e: add vm-put-docker-image to the vm library

---

docs/policy/rdt.md
sample-configs/cri-resmgr-configmap.example.yaml

Add more examples and advocate new shorthand notation for simple
allocations (omitting the 'all' keyword).

docs: improve rdt documentation

---

pkg/cpuallocator/allocator.go
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/sysfs/system.go
pkg/sysfs/utils.go

Improve detection of high priority CPUs. Examine
cpufreq/enenrgy_performance_profile setting of each CPU at system
discovery. All other than the least performance-oriented CPUs are
considered as prioritized. Some examples:
- if all cpus have the same epp value none will be flagged as prioritied
- cpus 0,1 are 'balance_performance', 2,3 are 'balance_power' and 4,5
are 'power' -> cpus 0-3 are flagger as priority cpus
Implements #552

Improve CPU prioritization

---

pkg/cri/resource-manager/control/page-migrate/page-migrate.go

Storing and retrieving the Pod ID is needed for properly discovering
the process IDs of tasks/processes belonging to a Kata container in
cgroupfs.

page-migrate: add cache-like container.GetPodID().

---

test/e2e/benchmarks.test-suite/memtier_benchmark/cri-resmgr.cfg
test/e2e/benchmarks.test-suite/memtier_benchmark/memtier-benchmark.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/n4c16/test01-memtier-stress-ng/code.var.sh
test/e2e/benchmarks.test-suite/memtier_benchmark/n4c16/test01-memtier-stress-ng/post-process.sh
test/e2e/benchmarks.test-suite/memtier_benchmark/n4c16/topology.var.json
test/e2e/benchmarks.test-suite/memtier_benchmark/redis-secret.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/redis-service.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/redis.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/stress-ng-benchmark.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/stress-ng.yaml.in
test/e2e/run.sh

The initial version of this benchmark needs configuring depending on the hardware where it runs on. Current `CPU`/`CPULIM` values in `code.var.sh` are suitable for testing on servers with ~50..200 CPU cores.

benchmark: add memtier_benchmark for memcached/redis

---

docs/policy/rdt.md
go.mod
go.sum
pkg/cri/resource-manager/control/rdt/rdt.go
sample-configs/cri-resmgr-configmap.example.yaml

TODO: Remove existing monitoring groups when changing from enabled to disabled. However, for symmetry, assign() should be called on all existing containers on re-configure.
Based on #567 
Also requires https://github.com/intel/goresctrl/pull/16

control/rdt: add option to disable rdt monitoring

---

pkg/cri/resource-manager/control/rdt/rdt.go

Assign container to the "system root" class if containers RDTClass is
set to an empty string. Root is the default for new containers that do
not have any class set so we should set (back) to root if class is
changed to empty.

control/rdt: empty class implies root class

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/control/rdt/rdt.go

- Take into account that the system root class always exists if rdt has
been initialized, even if the configuration contains no classes.
- Remove the special handling for class names matching Pod QoS class
names. Either the controller is disabled or not, the controller should
be agnostic to the class name.

control/rdt: fix and simplify handling of implicit disabling

---

go.mod
go.sum
pkg/cri/resource-manager/control/rdt/rdt.go

Causes obsolete resctrl groups to be deleted even if they are not empty.
Prevents configuration errors in case non-empty classes would be removed
from the config. Makes it possible e.g. to switch rdt to "implicitly
disabled mode" even if there are some running containers. This behavior
is justified as we now re-assign containers on every re-configure event
and containers will get correctly assigned if/when their rdt class
becomes available.

control/rdt: do forceful rdt (re-)configuration

---

pkg/cri/resource-manager/control/rdt/rdt.go

Postpone the call after rdt has been configured and we have the correct
config to check "idleness" from.

control/rdt: correct usage of checkIdle() in configNotify()

---

docs/requirements.txt

Make sure to use the same version everywhere in order to have the same
bugs everywhere.
Bump from v0.6.x to v0.7.x fixes an issue with links to external
markdown (.md) files.

docs: use an explicit version of recommonmark

---

docs/quick-start.md
docs/setup.md
pkg/cri/resource-manager/control/page-migrate/demoter.go
pkg/cri/resource-manager/control/page-migrate/page-migrate.go
pkg/cri/resource-manager/control/rdt/rdt.go
pkg/utils/cgroups.go

This branch adds support for Kata containers in CRI-RM, particularly detection and classification support for the cgroup and RDT controllers.
The solution proposed should solve issue #564

Kata container support

---

docs/policy/rdt.md
go.mod
go.sum
pkg/cri/resource-manager/control/rdt/rdt.go
sample-configs/cri-resmgr-configmap.example.yaml

Add a new 'mode' rdt config option to control the operation mode of the
controller. There are three possible modes:
- Disabled:  RDT controller is effectively disabled and containers will
not be assigned. When activating this mode, the controller
applies an empty rdt configuration removing all cri-rm
specific groups from the resctrl filesystem.
- Discovery: RDT controller detects existing non-cri-rm specific
classes from the resctrl filesystem and uses these.
CRI-RM will treat the configuration of these as read-only
and does not alter it.  Similarly to 'Disabled' mode, all
cri-rm specific groups from the resctrl filesystem are
dropped when this mode is activated.
- Full:      Full operating mode. RDT controller behaves like
previously. This is the default.
Depends on …

control/rdt: implement operating modes

---

pkg/cri/resource-manager/control/rdt/rdt.go

Assign container to the system root class if the class assignment fails.
The most probable reason is that the class specified for it is missing.
Otherwise the unassigned container(s) will inherit the resctrl group of
the container runtime itself which we want to avoid.  The system root
class is guaranteed to exist and is the obvious fallback default.
Supplements #581

rdt: use root class as a fallback to missing classes

---

test/e2e/benchmarks.test-suite/memtier_benchmark/memtier-benchmark.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/stress-ng-benchmark.yaml.in
test/e2e/benchmarks.test-suite/memtier_benchmark/stress-ng.yaml.in
test/e2e/besteffort.yaml.in
test/e2e/burstable.yaml.in
test/e2e/guaranteed.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test02-annotation-memory-type/memtype-guaranteed.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart/bb-coldstart.yaml.in
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion/bb-memload.yaml.in
test/e2e/policies.test-suite/memtier/n4c16/test03-simple-affinity/guaranteed+affinity.yaml.in
test/e2e/policies.test-suite/static-pools/cmk-exclusive.yaml.in
test/e2e/policies.test-suite/static-pools/cmk-isolate.yaml.in
test/e2e/policies.test-suite/static-pools/cmk-tolerating-guaranteed.yaml.in

- Missing imagePullPolicy can cause false negative results.
- Tests pull images only IfNotPresent.
- Reorder lines in pod yamls so that "image" is followed by
"imagePullPolicy".

e2e: set imagePullPolicy on every test pod

---

pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/policy/builtin/memtier/cache.go
pkg/cri/resource-manager/policy/builtin/memtier/coldstart_test.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go
pkg/cri/resource-manager/policy/flags.go
pkg/cri/resource-manager/policy/policy.go

This PR attempts to implement proper handling of the bounding/allowed CPU set
for the `memtier` policy. The patch set
- adds support for reading the bounding CPU set from a cgroup directory
- falls back to reallocating containers if reinstating allocations fails
- triggers rebuilding the topology pool if the reserved or allowed CPU set changes
Detecting a mismatch between the configuration of kubelet (`--cgroup-root`) and
CRI Resource Manager is not part of this patch set.

policy,memtier: better handling of bounding resource set for CPUs.

---

pkg/cri/resource-manager/policy/builtin/memtier/cache.go
pkg/cri/resource-manager/policy/builtin/memtier/cache_test.go
pkg/cri/resource-manager/policy/builtin/memtier/memtier-policy.go
pkg/cri/resource-manager/policy/builtin/memtier/node.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences_test.go
pkg/cri/resource-manager/policy/builtin/memtier/pools.go
pkg/cri/resource-manager/policy/builtin/memtier/pools_test.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go
test/e2e/policies.test-suite/memtier/c4pmem4/test02-annotation-memory-type/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test03-coldstart/code.var.sh
test/e2e/policies.test-suite/memtier/c4pmem4/test04-dynamic-page-demotion/code.var.sh
test/e2e/policies.test-suite/memtier/n4c16/test00-basic-placement/code.var.sh
test/e2e/policies.test-suite/memtier/n4c16/test01-always-fits/code.var.sh
test/e2e/policies.test-suite/memtier/n4c16/test02-shrink-and-grow-shared/code.var.sh
test/e2e/policies.test-suite/memtier/n4c16/test03-simple-affinity/code.var.sh
test/e2e/policies.test-suite/memtier/n4c16/test05-reserved-resources/code.var.sh
test/e2e/policies.test-suite/memtier/n4c16/test05-reserved-resources/cri-resmgr-reserved.cfg.in

- Pin kube-system and BestEffort pods to Reserved CPUs when Reserved
cpuset is defined.
- If Reserved cpuset is not defined, keep earlier behavior: use
shared CPUs.
- A pod running on reserved CPUs is assigned to a NUMA node with most
free reserved CPU resources per colocated reserved container.
- Reserved CPUs cannot be exclusively allocated.
- Introduce cpuType to pod-preferences to support handling processor
flavors in the future.
- Add e2e test for reserved CPUs.

memtier: implement reserved CPUs pool

---

pkg/cri/resource-manager/policy/builtin/memtier/pools.go

This breaks often due to this call in cache.go: [updateSharedAllocations(nil)](https://github.com/intel/cri-resource-manager/blob/master/pkg/cri/resource-manager/policy/builtin/memtier/cache.go#L92).

fix: nil pointer dereference on updateSharedAllocations(nil)

---

docs/policy/memtier.md
pkg/cri/resource-manager/policy/builtin/memtier/mocks_test.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences_test.go
pkg/cri/resource-manager/policy/builtin/memtier/resources.go

Prefer using the 'effective' syntax for isolated exclusive CPU, shared CPU, memory type
and cold start period annotated preferences. Remove support for 'elevation' in shared CPU
annotations. It was never implemented.

memtier: unify syntax for annotated preferences

---

docs/conf.py

Properly recognize a `[]()`-link to an `.md`-file with a `#`-prefixed element ID.
This will cause the generation of a proper link to the corresponding final `HTML`
element in the generated output, instead of a link to the base `.md`-file itself.

docs: recognize/handle .md-links to element IDs.

---

pkg/cri/resource-manager/events.go
pkg/cri/server/server.go

Explicitly flush logs after every CRI request and resource-manager event processed.

server,resource-manager: flush logs after every request/event processed.

---

docs/policy/memtier.md
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/memtier/pod-preferences_test.go

This PR is based on/requires PR #588.
Update the interpretation of shared/isolated CPU opt-in and opt-out annotations
(and global policy defaults) to produce less irregular and hopefully more intuitive
CPU allocation preferences.
TODO/Question:
Would it provide better usability to use a single explicit non-boolean annotation
(for instance `cpu-preferences`) to express all CPU allocation preferences ?

memtier: more regular annotation interpretation for CPU allocation preferences.

---

pkg/cri/resource-manager/control/rdt/rdt.go

Fix incorrect/inverted `containerID, podID` parameter order in call to `GetTasksInContainer()`.
Spotted and reported by Mihai Daniel Dodan (github.com/Dodan).

rdt: fix order of params passed to GetTasksInContainer().

---

pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

When dumping the tree of pools,
- dump grants and association types with all associated nodes (cpu+mem, cpuonly, memonly)
- omit dumping empty node memory sets
- omit dumping empty child lists

topology-aware: improved topology tree/node dump

---

pkg/log/klogcontrol/klogcontrol.go

When logging to a journald stream default to logging
without headers to avoid logging date and time stamp
twice.

klog: skip headers for journald by default.

---

cmd/cri-resmgr/cri-resource-manager.service.in

Increate journald log bursts to avoid losing messages
when running with extensive debugging enabled.

cri-resmgr: increase allowed service journal log bursts.

---

pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go

Normally it is enough to release stale containers and reallocate newly discovered
ones when we do our initial sync with the runtime during startup. However, when
switching the active policy is allowed and it does happen during startup, we need
to force reallocating everything. Otherwise containers already known and present
in the cache would not get properly updated by the newly activated policy.

resource-manager: force full reallocation when switching policies.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go

**Note:** This PR is also merged into stacked [PR #609](https://github.com/intel/cri-resource-manager/pull/609).
This PR fixes the allocation/assignment of resources to reserved containers in the kube-system namespace.

topology-aware: force reserved/kube-system containers to the root.

---

test/e2e/policies.test-suite/topology-aware/c4pmem4/test05-guarantee-memory/code.var.sh

**Note:** This PR is also merged into stacked [PR #609](https://github.com/intel/cri-resource-manager/pull/609).
This PR adds end-to-end tests to verify the basic functionality of the OOM-prevention memset expansion logic in the topology-aware policy.

e2e: add tests for memset expansion in topology-aware policy.

---

pkg/cri/relay/relay.go
pkg/cri/relay/runtime-service.go
pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go
pkg/cri/server/server.go
pkg/dump/dump.go
pkg/dump/dump_test.go

**Note:** This PR is also merged into stacked [PR #609](https://github.com/intel/cri-resource-manager/pull/609).
This PR adds extra data to dumped `CRI` messages to help disambiguate corresponding pairs of request/response messages.

resource-manager,dump: dump extra data for message disambiguation.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

**Note:** This PR is also merged into stacked [PR #609](https://github.com/intel/cri-resource-manager/pull/609).
This PR improves debug logging in the topology aware policy. In praticular, it
- changes debug logs to use container `PrettyName()`s
- produces more readable dumps of `memoryMaps`
- dumps the memory accounting state of pool tree nodes

topology-aware: better and more readable logs.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/cache.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

**Note 1:** This PR is stacked on [#615](https://github.com/intel/cri-resource-manager/pull/615). You probably want to review that separately first.
**Note 2:** This PR is also merged into stacked [PR #609](https://github.com/intel/cri-resource-manager/pull/609).
This PR
- fixes the memset expansion logic in `ExpandMemset()`
- fixes accounting to not leak resources on failed CPU allocation
- fixes accounting to not leak memory on (partially) failed memory allocation
- fixes a bug that double-charges pool tree nodes for already allocated memory
- adds debug logs to the memory accounting code

topology-aware: memory accounting and memset expansion fixes.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go
pkg/cri/resource-manager/requests.go

**Note 1:** This a stacked PR. You probably want to review the following underlying PRs separately first:
**Note 2:** This PR is also merged into stacked [PR #609](https://github.com/intel/cri-resource-manager/pull/609).
This PR adds code to intercept CRI `StopPodSandbox()` and `ListContainers()`
requests to detect better/earlier when a container is not longer running and to
release the resources of such a container.

resource-manager: catch containers earlier when they are gone.

---

test/e2e/policies.test-suite/podpools/n4c16/py_consts.var.py
test/e2e/policies.test-suite/podpools/n4c16/test01-basic-placement/code.var.sh
test/e2e/policies.test-suite/podpools/n4c16/test04-overbook-cpus/code.var.sh
test/e2e/policies.test-suite/podpools/n4c16/test05-agent-updates-config/code.var.sh

Update podpools tests and make them easy to update when CPU allocator behavior changes next time.
This PR runs on top of PR #602.

e2e: update podpools tests to pass with new cpuallocator

---

pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

Produce more human-comprehensible log messages wrt. memory requests/allocations.

topology-aware: use prettyMem() in log messages.

---

pkg/cri/resource-manager/requests.go

Save the cache as the last action in a successful startup sequence.

resource-manager: save cache at startup.

---

pkg/cri/resource-manager/requests.go

**Note:** This is a stacked PR. You probably want to review the following underlying PRs first:
This full stack of PRs fixes a number of CPU and memory accounting bugs in the topology-aware
policy. In particular it
- fix the logic for expanding container cpuset.mems for OOM-avoidance
- fixes CPU allocation/accounting leaks for failed allocations
- fixes memory allocation/accounting leaks for failed allocations
- fixes pools being double-charged for already allocated memory
Additionally, the stack of PRs
- intercepts CRI `StopPodSandbox` and `ListContainer` messages to detect gone containers earlier
- forces reserved/kube-system containers to the root pool
- improves disambiguation of CRI request/response pairs in message dumps
- improves both the extend and readability of debug logs in …

fixes: topology-aware policy cpu/memory accounting fixes.

---

pkg/sysfs/sst_if.go

Describes why we need that instead of using sysfs topology information.

pkg/sysfs: clarifying comment on getCPUMapping()

---

docs/policy/rdt.md
go.mod
go.sum
sample-configs/cri-resmgr-configmap.example.yaml

Update goresctrl to the latest revision which supports L2 CAT. There are no other (API) changes than new options in the configuration.

rdt: support L2 cache allocation

---

sample-configs/cri-resmgr-configmap.example.yaml

Comments starting from the beginning of line inside the configmap data
broke the yaml format.

sample-configs: make cri-resmgr-configmap.example.yaml usable

---

docs/requirements.txt

Sync Pygments version between local and containerized builds. Fixes
possible "lexer name 'toml' is not known" error in local builds.

docs: update Pygments requirements

---

demo/lib/distro.bash

This PR switches the fedora cloud image to 33 and the corresponding bootstrap commands
to use grubby for switching systemd to a non-unified v1/v2 cgroupfs mount.
We expect fedora users to have switched by now now to the latest which is version 33.
Since that is glibc-incompatible with the previous ones, switching the cloud image
as well allows running on fedora 33 hosts e2e tests in fedora 33 VMs.

fixes: fixes for fedora 33

---

pkg/cri/resource-manager/cache/utils.go

This change enables finding proper container cgroup directory with `container.GetCgroupDir()` on e2e/demo ubuntu/debian VMs.
The problem was found when trying to use future `blockio` from `goresctrl` like this:
```
blockio.SetContainerClass(c.GetCgroupDir(), class)
```

cache: add a directory to findContainerDir search path

---

demo/blockio/run.sh

When VM disk contents are small enough, md5sum scan may cause all data
to be cached before measuring md5sum I/O speed. That leads md5sum
process to exit/restart between measurements which prevents getting
reliable numbers.

blockio demo: always drop caches before measuring blockio speed

---

demo/blockio/run.sh

cri-resmgr that is installed from the source tree to a VM, is now
installed to /usr/local/bin. Fix detecting it from there, in addition
to /usr/bin.

blockio demo: fix detecting already installed cri-resmgr

---

demo/lib/host.bash
test/e2e/run.sh

This patch extends "vm=VMNAME test/e2e/run.sh debug" to
- Copy goresctrl sources to VMNAME.
- Add goresctrl source directory substitution on VM so that dlv will
find the sources.

e2e: add goresctrl debugging support to "run.sh debug"

---

demo/lib/command.bash

The current time returned by bash variable EPOCHREALTIME can contain
either "." or "," separator between seconds and microseconds (depending
on used locale), and because that value is feed directly to bc, then it
is possible that bc command will not understand the value and can return
"(standard_in) 1: syntax error"
if the current locale uses "," separator.
In order to fix this issue, set LC_NUMERIC=C so that bash uses always "."
when feeding the data to bc command.

e2e: lib: Use proper locale for bc to work

---

docs/developers-guide/e2e-test.md

The installation of govm needs to be done slightly differently
when using go 1.16

e2e: Fix govm installation documentation

---

demo/lib/distro.bash

This fixes issues that sometimes go is not fully functional due to
missing git.

e2e: always install git-core with golang

---

demo/lib/distro.bash

Asterisk was expanded by the shell in the vm.

e2e: fix error message after installing golang from tar

---

demo/lib/distro.bash

Reinstalling containerd does not fail anymore due to
Virtualization_containers being already in the repository list.

e2e: fix reinstalling containerd on opensuse

---

demo/lib/vm.bash

If VM_IP is set, check that we can run commands as root on the host.

e2e: enable running without govm if VM_IP is set

---

demo/lib/vm.bash

vm-install-runc supports installing runc from a package and from the
${runc_src} directory where it is created by "make".

e2e: add vm-install-runc

---

test/e2e/besteffort.yaml.in
test/e2e/burstable.yaml.in
test/e2e/guaranteed.yaml.in

Annotations can be added to besteffort, burstable and guaranteed pods
through ANN[0-9] environment variables. Example:
CPU=500m MEM=64M ANN0='my.key: "myvalue"' create guaranteed

e2e: support annotations in common pod templates

---

test/e2e/run.sh

This framework is not anymore only about CRI Resource Manager. This
is also about testing CRI Resource Manager features included in
container runtimes.

e2e: change e2e test framework title

---

demo/lib/vm.bash

The vm-check-source-files-changed function generalizes current
cri-resmgr binary check so that it can be applied to any local project
source directory and binary (containerd, crio, runc).

e2e: add function for checking if local binary is out-of-date

---

test/e2e/run_tests.sh

Test suite directories contain files varname.var* from which
environment variables are created for run.sh. This extension enables
using framework's common templating in variables when the file is
named "varname.var.in.*". Templating allows, for instance, expanding
environment values and giving default values when user has not
explicitly given them. As an example of both cases:
containerd_src.var.in.sh (sets containerd_src variable) contains
${containerd_src:-$GOPATH/src/github.com/containerd/containerd}

e2e: allow templating in test suite variable files

---

test/e2e/run_tests.sh

Enable test suites that do not use cri-resmgr in their CRI pipeline.

e2e: cri-resource-manager configuration is optional in test suites

---

demo/lib/vm.bash
test/e2e/run.sh
test/e2e/run_tests.sh

- Install locally built crio, containerd, runc, and cri-resmgr from
explictly given source directories (<project>_src variables).
- "run.sh debug" installs sources from <project>_src directories.
- Add k8scri to specify the CRI pipe that run.sh sets up on vm.
- Add on_k8s_online to hook when Kubernetes is running on vm.
**Note**: PRs up to 681 include features required by this change.

e2e: support CRI-O, containerd, and containerd + cri-resmgr as NRI

---

test/e2e/policies.test-suite/topology-aware/n4c16/test05-reserved-resources/code.var.sh

The reserved resources test left the vm in a configuration that was
likely to cause failures on tests executed after it. This fix restores
the configuration when this test passes. Leave configuration as is on
failure to help debugging.

e2e: clean up vm after successful reserved-resources test run

---

test/e2e/policies.test-suite/topology-aware/n4c16/test08-isolcpus/code.var.sh

Sometimes vm needs more time to get kubelet up and running after
restart.

e2e: improve isolcpus test robustness

---

scripts/testing/kube-cgroups

I've been using this script for testing blkio cgroup parameters. I think it could be useful for you too, as it shows pretty clearly cpuset.cpus/mems for every pod/container, too.

scripts: kube-cgroups prints cgroup entries per pod/container

---

demo/lib/distro.bash
demo/lib/vm.bash
test/e2e/run.sh

Fixes AWS SLES VM support as required in issue #686.
Also enables running SLES on local VMs if the user has downloaded SLES cloud image (requires registration).

e2e: add support for distro=sles

---

demo/lib/distro.bash
demo/lib/vm.bash
test/e2e/run.sh

- If a reinstall variable is set for any package, it will be forced to reinstall on the system.
- OpenSUSE / SLES install runc from Virtualization_containers.
- Reinstalling k8s means scrapping and recreating the cluster on VM -- in addition to reinstalling kubeadm, kubectl and kubelet.
- Refactor: get rid of screen-install-k8s.
Implemented on top of #688.
Implements suggested reinstall feature in issue #686 .

e2e: enable reinstalling pretty much everything on VMs

---

demo/lib/distro.bash
test/e2e/run.sh

- Supported initially on ubuntu-* and debian-* distros.
- Update help to include k8s and distro.

e2e: add support for k8s=X.Y.Z to set Kubernetes version

---

scripts/testing/kube-cgroups

kube-cgroups prints pods/containers with their cgroups configuration.
Before this change it found the configurations only for containers
managed by containerd. This change makes it work similarly with CRI-O
containers, too.
This change is needed for running
test/e2e$ k8scri=crio ./run_tests.sh blockio.test-suite

scripts: add CRI-O support to kube-cgroups

---

demo/lib/distro.bash
test/e2e/run.sh

Don't insist installing cri-o from sources. Add support for
installing cri-o from distro repos for Fedora and CentOS-8.

e2e: allow installing cri-o from distro repos.

---

demo/lib/distro.bash

Simply fetch keys with `curl -L` instead of plain `curl`.

e2e: follow HTTP redirects when fetching apt repo keys.

---

test/e2e/run.sh
test/e2e/run_tests.sh

Add support for k8scri='crio&cri-resmgr'. In this CRI pipe kubelet
will connect to CRI-O, and cri-resmgr runs as an NRI plugin.
Example:
crio_src=/path/to/CRI-O-with-NRI-support \
crirm_src=/path/to/cri-resource-manager-with-NRI-support \
k8scri='crio&cri-resmgr' \
./run_tests.sh policies.test-suite/topology-aware

e2e: support running tests with CRI-O and cri-resmgr in NRI mode

---

demo/lib/distro.bash

Tested to work on `distro=fedora` and `distro=centos-8`.

e2e: fix sysctl settings that break cilium CNI on Fedora

---

demo/lib/distro.bash

sysctl may fail when rp_filter is not available in the kernel.

e2e: fix cloud-init error on distro=debian-sid

---

pkg/cri/resource-manager/control/rdt/rdt.go

Search RDT classes based on their name, not based on their index in our internal array. Also, update code comments.

control/rdt: fix discovery of pod qos classes in discovery mode

---

.github/workflows/verify.yml

The linter output on un-buildable tests can be really confusing.

github: run tests before golanci-lint

---

demo/lib/distro.bash

Explicitly force apt-get (install) into non-interactive mode.
This should fix bootstrapping a cluster on debian sid.

distro: force non-interactive 'apt-get install'.

---

demo/lib/distro.bash
test/e2e/run.sh

Ubuntu 21.04 installs with GLIBC_2.33. This helps testing cri-resmgr
on Ubuntu when it has been built on a host that has newer libc than
the default Ubuntu 20.04 LTS (GLIBC_2.30) or 20.10 (GLIBC_2.32).

e2e: add support for distro=ubuntu-21.04

---

dockerfiles/cross-build/Dockerfile.fedora

dockerfiles: use fedora:latest for cross-builds.

0.6.0 release preparation: use latest fedora image for cross-build.

---

demo/lib/distro.bash

distro: always try setting 'SystemdCgroup = true' for containerd.

0.6.0 release preparation: always try to enable 'SystemdCgroup = true' for tests with containerd.

---

docs/conf.py
docs/requirements.txt
docs/setup.md

Fix recent docs build breakage by switching from the phased out `recommonmark` to `MyST-Parser` and by ugrading from `Sphinx 3.2.1` to `3.5.4` which is the latest in the 3.x series.

docs: fix docs Sphinx build breaking in github actions.

---

demo/lib/vm.bash

golang update on e2e tests broke fetching containernetworking plugins
with go get.

e2e: fix installing containernetworking with go 1.16

---

pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/podpools/metrics.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/resource-manager.go
pkg/policycollector/collector.go
pkg/procstats/procstats.go

1. Add APIs DescribeMetrics, PollMetrics, CollectMetrics in Policy
and Backend interface. It aims to define policy-specific metrics
and expose them for monitoring.
2. After setupPolicy successfully, ResourceManager will register
the policy-specific collector to metrics if the policy has defined.
3. Add the package procstats to calculate CPU utilization of each
thread by using the time statistics from /proc/stat.
Signed-off-by: Huang Rui <rui1.huang@intel.com>

Monitor the pool CPU usage for podpools-policy.

---

demo/lib/distro.bash

If user has not specified cri-o sources, then system specified
cri-o package is used but it is not enabled by default in centos-8.
This means that in second boot of the VM, the kube environment does
not start properly because cri-o is not started automatically.
Fix this by enabling cri-o in systemd so that it is started at boot.

e2e: Enable cri-o in centos-8

---

scripts/build/get-buildid

Otherwise you might get version numbers like
"failed to determine version from any source" in the Makefile which
breaks things.

scripts/build/get-buildid: return unknown version

---

pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/builtin/podpools/metrics.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static-pools/stp-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/policy.go
pkg/procstats/procstats.go

Modify policys-specific to policy-specific.
Improve the parsing process on /proc/cpu.
Signed-off-by: Huang Rui <rui1.huang@intel.com>

Correct one typo and two nitpicks.

---

demo/lib/host.bash

If user has specified VM_IP when starting run.sh, then there is
no need to try to resolve the IP address of the VM. This allows
the script to be used to configure non govm based hosts.

e2e: Do not try to use govm if user has specified the VM address

---

demo/lib/distro.bash
demo/lib/host.bash
demo/lib/vm.bash
test/e2e/run.sh

These fix couple of issues when the k8s is installed to a non VM host.
* The proxies can be setup automatically if `setup_proxies=1` is set when invoking `run.sh`
* Setup pre-flight reqs like ip_forward setting in the host

e2e: Fixes for non govm usage

---

test/e2e/policies.test-suite/podpools/n4c16/test06-prometheus-metrics/code.var.sh
test/e2e/policies.test-suite/podpools/n4c16/test06-prometheus-metrics/podpools-metrics.cfg
test/e2e/policies.test-suite/podpools/podpools-busybox.yaml.in

This patch implements end-to-end test for PR #692.
Prerequisites:
- docker
- govm
How to install prerequisites on Ubuntu and Debian:
```
sudo apt install -y docker.io git-core golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
GO111MODULE=off go get -d github.com/govm-project/govm && cd $GOPATH/src/github.com/govm-project/govm && go mod tidy && go mod download && go install && cd .. && docker build govm -f govm/Dockerfile -t govm/govm:latest
```
Usage:
```
test/e2e$ ./run_tests.sh policies.test-suite/podpools/n4c16/test06-prometheus-metrics
```

e2e: podpools metrics test

---

pkg/cri/resource-manager/cache/affinity.go
pkg/cri/resource-manager/cache/affinity_test.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go

The current implementation fails to parse affinity annotations properly. In the worst case this can lead to the misinterpretation of annotations. This PR updates affinity handling to fix this.
- cache:
- parse affinity annotations with a strict YAML parser
- propagate parse errors back to the entity querying affinities (a policy)
- add minimal test case to verify parsing/failing valid/invalid affinity annotations
- topology-aware policy:
- properly fail allocations for containers with invalid affinity annotations

fixes: properly reject containers with invalid/unparsable affinity annotations.

---

demo/lib/distro.bash

- Bind-mount /opt/cni/bin in Fedora also when installing crio, in
addition to containerd.
- Fixes crio CNI detection issue in Fedora.

e2e: containernetworkplugins in /opt/cni/bin in fedora

---

demo/lib/vm.bash

Update cilium installation to use cilium cli as instructed in up-to-date cilium documentation.
This also upates cilium from 1.9 to 1.11.

e2e: fix cilium installation and update to cilium v1.11

---

demo/lib/distro.bash
demo/lib/vm.bash
test/e2e/run.sh

Similarly to the `k8scri` parameter, allow user to define which CNI to install on new cluster by setting `k8scni`.
This patch also adds support to the flannel CNI.
Setting `reinstall_bootstrap` is added to keep our shellcheck (git hook) happy.

e2e: support k8scni=<cilium|weavenet|flannel>

---

demo/lib/vm.bash
test/e2e/run.sh

- Enable running a binary on VM, even if the binary would have been
built with later glibc than available in the VM.
- Example: installing a locally built containerd to a distro with
an old glibc:
containerd_src=.../github.com/containerd/containerd \
on_cri_install='vm-install-glibc 2.34
vm-set-glibc 2.34 /usr/bin/containerd
vm-command "systemctl restart containerd"'

e2e: add vm-install-glibc, vm-set-glibc and on_*_install hooks

---

go.mod
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/resource-manager.go
pkg/pidfile/pidfile.go
pkg/pidfile/pidfile_test.go

Implement basic PID file handling. Write a PID file upon successful startup. If we fail to start up due to an existing active socket, try to read the process ID of the running instance from the PID file. If this succeeds write an diagnostic/error message with the read process ID.

resmgr: write a PID file upon successful startup.

---

scripts/testing/pairwise
test/e2e/run_all_configurations.sh

- Test all distro, k8scni and k8scri values.
- Testing all supported combinations of values is very
expensive (takes several days), but testing every value only in a
single case gives poor coverage. Testing full pairwise coverage in all
values is a reasonable compromise. For instance, if there is a CNI
that does not work in a distro, we well catch that error.
- The number of tests to be executed will grow slowly even if new
variables are added. In case of all combinations this number would
grow exponentially.

e2e: add a test for distro/cni/cri combinations

---

demo/lib/vm.bash

Before this patch locally built containerd and crio were always
installed to /usr/bin on vm. This caused problems in distros where
packages install these runtimes somewhere else, for instance under
/sbin.
This patch verifies which containerd and crio binaries are used on the
vm and replaces those with local builds when calling vm-install-cri
with containerd_src or crio_src environment variables set.

e2e: vm-install-cri replaces original containerd/crio binary

---

pkg/cri/resource-manager/resource-manager.go
pkg/cri/server/server.go
pkg/utils/net.go
test/functional/fake_cri_server_test.go

Invert active socket test logic by testing if connecting to the socket fails with ECONNREFUSED instead of going through the full gRPC stack and checking if a connection can be established.
This PR should fix the apparent misbehavior for the corner case described [in this comment](https://github.com/intel/cri-resource-manager/pull/756#pullrequestreview-844621132).

fixes: better socket probing.

---

.githooks/pre-commit.d/20-go-version

Add a hook to check the consistency of declared golang version requirement vs. the one used in github workflows. No need to always wait for the already slow and overloaded github workers to run our tests till failure then let us know we forgot to update the other.

.githooks: add hook to check go version conistency.

---

.github/workflows/verify.yml

They're unneeded and just causing unpredictable behavior by doing
random-ish package updates.

github: drop unnecessary CI steps

---

.github/workflows/verify.yml
docs/conf.py
docs/releases/conf.py
docs/requirements.txt
docs/setup.md

Backports from master to get CI to pass muster
1. docs: use myst markdown parser for docs/releases too
Supplements 09cc1ee31db37f2f634f8a58d3f7b46704764b0f.
(cherry picked from commit 009a83eb65cf3e9cf39bc4766fb114e782e60bd2)
2. docs: update to sphinx 3.5.4.
(cherry picked from commit bf27672cff7de3b7b3f6745d4ac522ba3c5fc1c2)
3. docs: fix recommonmark breaking doc build on github.
An unfixed upstream recommonmark bug causes warnings during
'make site-build'/sphinx doc generation. These warnings are
treated as errors in github actions, so they can break test
builds of recent PRs. Fix this by switching to MyST-Parser.
See https://github.com/readthedocs/recommonmark/issues/177
for a miminal explanation of the bug.
See https://github.com/readthedocs/recommonmark/issues/221
for background …

[release-0.6] backport CI fixes

---

docs/developers-guide/architecture.md
docs/policy/cpu-allocator.md
docs/policy/rdt.md
docs/policy/topology-aware.md
docs/quick-start.md
docs/reference/configuration-reference.md
docs/setup.md
sample-configs/cri-resmgr-configmap.example.yaml

* fix indentation
(cherry picked from commit 4f0be74a53e3ce460709aed25b02f9e3eb7887c1)
* fix typos, indentation etc.
(cherry picked from commit 706aa60f02a935ad92f4a6cd3aa28c92d81e0427)

[release-0.6] docs: Fix doc and example config typos/indentation

---

pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Only write shared CPU information to resource.sh if there
are shared CPUs allocated to the container.

topology-aware: Do not advertise shared CPUs if there are none

---

pkg/cri/resource-manager/policy/builtin/podpools/podpools-policy.go
test/e2e/policies.test-suite/podpools/n4c16/test07-custom-default-pool/code.var.sh
test/e2e/policies.test-suite/podpools/n4c16/test07-custom-default-pool/podpools-custom-default.cfg

- This change enables easy node configuration by using allowing syntax
"Instances: 100%" in user-defined pod pools. This notation means
"allocate all the remaining CPUs to this pool".
- The behavior is the same as previously, if the CPUs of the built-in
"default" pool are not customized by the user.
- The behavior differs from previous when a new set of CPUs is
allocated to the "default" pool, that is, CPUs of the default pool and
the reserved pool are disjoint. The previous implementation did not
subtract these default CPUs from the CPU count that is the basis
for "n %" notation. As a result, it was impossible to guess the
percentage that would mean "all the rest CPUs" when core count varies.

podpools: never count default pool CPUs in Instances percentages

---

pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go

The CPU type field was not copied when cloning the grant.

topology-aware: Clone also CPU type in grant

---

demo/lib/topology.py

- Prevent shell expansion of process pattern in case there happens to
be a file that matches the pattern.

e2e: fix podXcY allowed resources finder

---

cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile

Use statically linked binaries in the agent and webhook container
images. We now have scratch-based images than only contain one file
(which is the agent or webhook binary) - clean and simple. With this we
also ditch the cumbersome clearlinux based build which does not even
support go v1.17 (or later).

Statically linked binaries in container images

---

go.mod
go.sum
pkg/sysfs/system.go

This fixes compilation error because goresctrl SST discovery API was changed and now we are using the latest version.

Fix SST discovery

---

pkg/cpuallocator/allocator.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/sysfs/system.go

Earlier code manipulated full SST info in CPU discovery, but this
is not needed as we can just use the pointer to SST info in the code.
This clarifies the usage, as the SstPackageInfo struct contains a slice
which can confuse the user if SstPackageInfo is not passed around as a
pointer value. This also saves some tiny amount of memory.

sst: Pass around pointer to SST info struct

---

pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pod-preferences_test.go

Allow user to add pod annotations that cause the CPUs to be
allocated from reserved pool.

topology-aware: Add support for reserved CPU annotations

---

demo/lib/vm.bash

- Use "go install" instead of "go get".
- Update dlv configuration file syntax to work with latest dlv.
- Now crirm_src=/path/to/project vm=vm-name ./run.sh debug
works again: copies sources to vm and sets up dlv for debugging.

e2e: update ./run.sh debug to work with recent golang and dlv

---

docs/setup.md
pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go
test/functional/e2e_test.go
test/functional/fake_cri_server_test.go

Disallow talking to/proxying for unknown runtimes, unless explicitly told to do so on the command line. This could save us quite a bit of time from chasing ghosts.
Inspired by an idea from @jukkar over a lunch discussion. Thanks !

resmgr: disallow talking to untested runtimes by default.

---

demo/lib/distro.bash
demo/lib/vm.bash
test/e2e/run.sh

If k8smaster environment variable is set, test/e2e/run.sh will join
new vm to an existing cluster instead of creating its own single-node
cluster.

e2e: enable running tests on multi-node clusters

---

test/e2e/run.sh

- Forcefully deletes a namespace whose deletion has been stuck in the
"Terminating" phase.

e2e: add kubectl-force-delete()

---

go.mod
go.sum
pkg/cri/resource-manager/control/cpu/api.go
pkg/cri/resource-manager/control/cpu/cpu.go

Support uncore frequency limits in the cpu controller. This patch adds
new 'uncoreMinFreq' and 'uncoreMaxFreq' fields to the cpu class
configuration.
Uncore frequency limits are only controllable on the cpu die level in
the HW. When resolving the per-die effective uncore frequency the
controller prefers performance i.e. selects the highest requested value.
For every die it selects the highest value (for both min and max) of all
cpu classes that are effective on that die.
An example configuration with uncore limits:
```
cpu:
classes:
high-prio:
minFreq: 2000000
maxFreq: 5000000
uncoreMinFreq: 2000000
uncoreMaxFreq: 2400000
low-prio:
minFreq: 1000000
maxFreq: 1500000
uncoreMinFreq: 1200000
uncoreMaxFreq: 1800000
```

control/cpu: add uncore frequency controls

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
pkg/cri/resource-manager/policy/builtin/balloons/fillmethod.go
pkg/cri/resource-manager/policy/builtin/balloons/flags.go
sample-configs/balloons-policy.cfg
test/e2e/policies.test-suite/balloons/n4c16/test05-namespace/balloons-namespace.cfg
test/e2e/policies.test-suite/balloons/n4c16/test05-namespace/code.var.sh

- Enables preferring new balloon instances of the same balloon type
for containers that run in different namespaces. At the same time,
starts preferring to place containers in the same namespace to the
same balloon instance.

balloons: add PreferSpreadingDifferentNamespace option

---

test/e2e/policies.test-suite/topology-aware/n4c16/test00-basic-placement/code.var.sh

Properly clean up pods and restore default configuration after having run the namespace-colocation tests.

test/e2e: clean up after namespace colocation tests.

---

test/e2e/policies.test-suite/balloons/cri-resmgr.cfg
test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/balloons-metrics.cfg
test/e2e/policies.test-suite/balloons/n4c16/test03-reserved/balloons-reserved.cfg
test/e2e/policies.test-suite/podpools/cri-resmgr.cfg
test/e2e/policies.test-suite/podpools/n4c16/test06-prometheus-metrics/podpools-metrics.cfg
test/e2e/policies.test-suite/podpools/n4c16/test07-custom-default-pool/podpools-custom-default.cfg
test/e2e/policies.test-suite/static-pools/cri-resmgr.cfg
test/e2e/policies.test-suite/static-pools/n4c16/cri-resmgr-static-pools.cfg
test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion-deprecated-syntax/cri-resmgr-dynamic-page-demotion.cfg
test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion/cri-resmgr-dynamic-page-demotion.cfg
test/e2e/policies.test-suite/topology-aware/cri-resmgr.cfg

Omit klog headers from the generated policy test suite log files.

test/e2e: produce more readable policy test suite logs.

---

test/e2e/policies.test-suite/topology-aware/n4c16/test00-basic-placement/cri-resmgr.cfg.in

Don't use invalid 'cpu: 0' CPU reservation. Don't even use a test-specific configuration file.
Instead, parameterize the top-level one correctly for the test case.

test/e2e: don't use invalid '0' CPU reservation.

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy_test.go
pkg/cri/resource-manager/policy/builtin/balloons/flags.go

- Recreate balloons and reassign workloads only if necessary.
- CPU class of balloon types can be switched without reassigning
workloads.

balloons: improve dynamic configuration update

---

test/e2e/policies.test-suite/balloons/balloons-configmap.yaml.in
test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh
test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh
test/e2e/policies.test-suite/balloons/verify.source.sh

- Add new test that changes balloons and CPU configurations using a
config map.
- Refactor verify-metrics functions to a common source file.

e2e: add test for dynamic balloons configuration update

---

test/e2e/run.sh

Previous behavior produced an union of allowed resources if there were
several containers running with the same name. This
feature/consequence was not used, but it produced unnecessary trouble
in debugging tests that fail due to unclean test environment.

e2e: ambigious allowed resources for each name is an error

---

test/e2e/policies.test-suite/podpools/n4c16/test06-prometheus-metrics/code.var.sh

- Also suppress cgroup_* lines from metrics output.

e2e: fix log parsing in podpools test05-prometheus-metrics

---

cmd/cri-resmgr-webhook/webhook-deployment.yaml

Node role "master" has been changed to "control-plane" in Kubernetes.

webhook: update example deployment node selector and toleration

---

dockerfiles/cross-build/Dockerfile.centos-8.in

Patch centos-8 repository paths in the cross-build docker image.

cross-build: fixup centos-8 repos.

---

demo/lib/vm.bash
test/e2e/policies.test-suite/topology-aware/n4c16/test08-isolcpus/code.var.sh

Be more insistent when rebooting a VM node for/between test cases. Use the newly introduced `vm-force-restart` instead of `vm-reboot`. In practice, if the test node is a govm-managed virtual machine, this will force the node to reboot with these steps:
1. `vm-command "shutdown -h now"`
2. `sleep 10`
3. `vm-monitor system_reset`
4. `host-wait-vm-ssh-server`
If the test node is not a govm-managed virtual machine `vm-force-restart` falls back to `vm-reboot`.

test/e2e: try rebooting harder for/after isolcpu tests.

---

Makefile
cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile

Parse the golang version to be used in the builder image from go.mod.
Keeps it always in sync.
(cherry picked from commit 3772f63d7aab2ba1076f459cb18fb22737a1a9f3)

images: take go version from go.mod

---

cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile

We use scratch as the base image now so now dynamically loaded libs are
available.

images: build statically linked binaries

---

Makefile

This fixes build of agent and webhook images. Otherwise they will fail
because go-build is not able to find the vcs information. Could be
handled with '-buildvcs=false' build flag but just removing chdir seems
simpler. Plus, we get the vcs information in the go binary.

Makefile: don't change dir when running go build

---

Makefile
cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile

- images: build statically linked binaries
We use scratch as the base image now so now dynamically loaded libs are
available.
- Makefile: don't change dir when running go build
This fixes build of agent and webhook images. Otherwise they will fail
because go-build is not able to find the vcs information. Could be
handled with '-buildvcs=false' build flag but just removing chdir seems
simpler. Plus, we get the vcs information in the go binary.

[release 0.7] backport image building fixes

---

Makefile

Otherwise tests might fail because of library version incompatibilities
wrt build host vs the container image that we're running the binaries.

Makefile: use statically linked binaries in e2e-tests

---

Makefile

Otherwise tests might fail because of library version incompatibilities
wrt build host vs the container image that we're running the binaries.
(cherry picked from commit 62a895544fa700f6916f7f17722610727f7b02f1)

[release-0.7] Makefile: use statically linked binaries in e2e-tests

---

docs/policy/balloons.md
go.mod
go.sum

- docs: improve balloons documentation
- Describe how the policy works.
- Document relevant configuration parameters.
- Add CPU classes.
(cherry picked from commit https://github.com/intel/cri-resource-manager/commit/c2ecc4f12279c91768d73b090983e9079af9a64a)
- go-mod: update go-restful
(cherry picked from commit https://github.com/intel/cri-resource-manager/commit/0b2fa6a126891e45b5c329163a9ee7e0d15c66c2)

[release-0.7] backport fixes from master

---

Jenkinsfile

So far we've only built container images from tags. This patch adds
special handling for the master branch so that container images built
from it are tagged with *:devel tag (instead of *:master). This naming
matches what we have in documentation, for example.

jenkinsfile: build *:devel images from master branch

---

pkg/cri/resource-manager/resource-manager.go

Allow optional unix socket qualifier for runtime, image and relay socket paths (by stripping any `unix://`-prefix).

resmgr: allow optional unix://-prefix for socket path options.

---

Jenkinsfile

Jenkins was unhappy with mixing in if-else in the declarative-style
pipeline definition. Try fixing it with imperative style.
#876 did not work as expected:
```
WorkflowScript: 14: Expected a step @ line 14, column 21.
if (env.BRANCH_NAME == 'master') {
^
```

jenkinsfile: fix the structure

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/requests.go

Don't crash during runtime state synchronization if the runtime fails to provide any useful pod status data (cgroup parent dir).
This same fix should protect against potentiallymalicious clients sending RunPodSandbox requests with nil Config or Config.Metadata.

release-0.6: cache: don't crash if pod has no status data.

---

pkg/cri/relay/relay.go
pkg/cri/resource-manager/flags.go

Make the image socket default to the current value of the runtime socket instead of the default value of the runtime socket. With this in place, changing only the value of the runtime socket changes the value of the image socket as well. In particular, this avoids `cri-resmgr --runtime-socket /var/run/crio/crio.sock` being a synonym for the insane `cri-resmgr --runtime-socket /var/run/crio/crio.sock --image-socket /var/run/containerd/containerd.sock` setup.

resmgr,relay: make image socket default to runtime one.

---

pkg/cri/resource-manager/agent/agent.go
pkg/cri/resource-manager/config/server.go
pkg/cri/resource-manager/policy/builtin/static-pools/node.go

This patch set allows one to disable the incoming and outgoing config/agent interfaces by explicitly setting the corresponding command line options to `"disabled"` or `""`.

resmgr: allow disabling the agent ingress and egress interfaces.

---

test/e2e/policies.test-suite/check-correct-policy.source.sh

E2E tests generally avoid restarting cri-resmgr for faster execution. This causes false FAILs when the same vm runs one test from policy A followed by another test from policy B without forced cri-resmgr restarting. This patch adds a script that run_tests.sh imports automatically when running any test from the policies test suite. The script checks if vm is running cri-resmgr with different policy than what next test expects, and if so, restarts cri-resmgr with cache cleared when needed.

e2e: check if cri-resmgr is expected to run with different policy

---

pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/requests.go

Don't crash during runtime state synchronization if the runtime fails to provide any useful pod status data (cgroup parent dir).
This same fix should protect against potentiallymalicious clients sending RunPodSandbox requests with nil Config or Config.Metadata.
This PR is #886 cherry-picked to release-0.7.

release-0.7: cache: don't crash if pod has no status data.

---

CODEOWNERS

Remove those previous owners who are nowadays mostly guilty by association.

CODEOWNERS: update maintainers.

---

test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh
test/e2e/policies.test-suite/balloons/n4c16/test07-maxballoons/code.var.sh

Make sure all pods are cleared when test starts and ends in order not to affect or get affected from other tests.

e2e: balloons: Cleanup pods in the tests

---

sample-configs/balloons-policy.cfg

Without this fix, running example fails with following error:
Steps to reproduce:
```
go run ./cmd/cri-resmgr --force-config sample-configs/balloons-policy.cfg
```
```
F0926 11:34:21.853955  214282 main.go:85] failed to create resource manager instance: resource-manager: failed to load forced configuration sample-configs/balloons-policy.cfg: config error: failed to apply configuration from file: config error: failed to load configuration from file "sample-configs/balloons-policy.cfg": error converting YAML to JSON: yaml: line 54: found a tab character that violates indentation
exit status 1
```

Replace tabs with spaces in broken balloons-policy.cfg example

---

demo/lib/distro.bash
test/e2e/run.sh

Following error was seen when trying to install Ubuntu 21.04 so remove support for it.
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security Release' no longer has a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute Release' no longer has a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-updates Release' no longer has a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-backports Release' does not have a Release file.

e2e: Remove Ubuntu 21.04 support

---

demo/lib/distro.bash

Extending no_proxy fixes a problem of running minikube in a Ubuntu VM behind a proxy.

e2e: add .internal and 192.168.0.0/12 to no_proxy

---

demo/lib/distro.bash

distro-install-kernel-dev prepares VM for building the latest kernel using distribution's current kernel configuration as a starting point.

e2e: add debian support for distro-install-kernel-dev

---

pkg/cri/resource-manager/flags.go

Fix help string for `--force-config` command line option.

resmgr: fix forced-config option description.

---

pkg/cri/resource-manager/flags.go
pkg/cri/resource-manager/resource-manager.go
pkg/sysfs/system.go
pkg/topology/topology.go
pkg/topology/topology_test.go

Allow overriding the default `sysfs` mount point using the newly introduced `--sysfs-root $dir` command line option. When used, the real host sysfs should be available/mounted as `$dir/sys`.
Target usage for this is to allow an NRI-enabled `cri-resmgr` to run as  a `DaemonSet` inside a container, yet be able to do proper HW-discovery using the full `sysfs` of the host.

resmgr: make sysfs/other hostfs pseudoroot directory configurable on the command line.

---

demo/lib/distro.bash
demo/lib/vm.bash

- Tested on debian, fedora and ubuntu.
- Example: distro=fedora on_vm_online=' vm-install-minikube; vm-create-minikube-cluster; vm-command "minikube kubectl -- get pods -A"; exit' test/e2e/run.sh interactive

e2e: add vm-install-minikube and vm-create-minikube-cluster

---

cmd/cri-resmgr-agent/main.go

As requested by Pawel [here](https://github.com/intel/cri-resource-manager/pull/903#issuecomment-1302567997)...

cri-resmgr-agent: print version info on startup.

---

demo/lib/vm.bash

Ubuntu 22.04 has known issues when trying to use -vga qxl with kvm. We do not need VGA for anything, so let's stop using qxl.

e2e: run Qemu with -nographic instead of -vga qxl

---

.gitignore

Intentionally ignore CRI-RM static binaries from git.
Those binaries could appear on the local repository
for example after `make build-static`.

Don't track static binaries in Git

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
test/e2e/policies.test-suite/balloons/n4c16/test09-isolated/balloons-isolated.cfg
test/e2e/policies.test-suite/balloons/n4c16/test09-isolated/code.var.sh

When a balloon type has PreferNewBalloon set, prefer assigning a container to an empty existing balloons over to a new ones. Without this change the best balloon instances (created due to MinBalloons > 0) are left empty until new balloon instances cannot be created anymore.

balloons: prefer an empty existing balloon over creating new

---

pkg/cri/resource-manager/control/memory/memory.go

Check and return an error if the kernels lack the top tier memory control knob. This should cause the control setup code to disable the top tier memory controller and prevent reoccuring warning/error messages whenever we put policy decision in practice.

control/memory: check top tier memory control on startup.

---

demo/lib/host.bash

Remove the qemu-version verifier container when it exits.
Otherwise, we end up with some garbage collected when
running e2e tests locally.

Remove the qemu-version verifier  container when it exits

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
test/e2e/policies.test-suite/balloons/n4c16/test08-numa/balloons-numa.cfg
test/e2e/policies.test-suite/balloons/n4c16/test08-numa/code.var.sh

Keep at least 1 CPU in every balloon that has containers, even if the sum of requested CPUs of the containers would be 0. Otherwise we would allow cpuset of a balloon to become empty, and thus the CPUs of those containers would not be pinned anymore.

balloons: fix empty cpuset of a balloon that has containers

---

demo/lib/vm.bash

It does not on Ubuntu 18.04... which breaks e2e tests there.

demo/lib: don't assume pidof accepts -q.

---

docs/Dockerfile
docs/conf.py
docs/requirements.txt

Update Sphinx and the other docs dependencies to their latest released versions.

docs: update sphinx to v5.3.0

---

scripts/testing/pairwise

This PR is #778 rebased on the latest master.
- Taking triplet coverage into account improves data coverage without increasing the number of parameter sets.
- As a downside, this implementation is naive and may cause performance problems with large data sets.

[rebased #778] scripts: pairwise maximizes covered triplets

---

pkg/cri/client/client.go
pkg/cri/client/v1/client.go
pkg/cri/client/v1alpha2/client.go
pkg/cri/relay/image-service.go
pkg/cri/relay/runtime-service.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/container.go
pkg/cri/resource-manager/cache/pod.go
pkg/cri/resource-manager/cache/utils.go
pkg/cri/resource-manager/control/cri/cri.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/requests.go
pkg/cri/server/server.go
pkg/cri/server/services.go
pkg/cri/server/v1alpha2/server.go
test/functional/e2e_test.go
test/functional/fake_cri_server_test.go

Switch the native/internal representation of pods and containers everywhere to CRI v1.
Implement ingress and egress protocol conversion between v1alpha2 and v1 to support
both pre-v1 clients and runtimes.

pkg/cri: switch internals to CRI v1, add ingress/egress v1/v1alpha2 CRI conversion.

---

pkg/cri/client/v1/client.go
pkg/cri/client/v1alpha2/client.go
pkg/cri/relay/runtime-service.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cache.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/server/services.go
test/functional/fake_cri_server_test.go

**Notes:** This PR depends/is stacked on #934. Please review / merge that one first.
Do not save and especially don't restore policy configuration as policy-specific data. It silently overwrites the effective configuration during policy startup. This cases really tricky to debug failures in some tests that use forced configuration to alter behavior but are not run first after startup.

topology-aware: don't restore config on startup

---

test/e2e/policies.test-suite/balloons/n4c32/test01-dynamic-baloons/balloons-dynamic.cfg
test/e2e/policies.test-suite/balloons/n4c32/test01-dynamic-baloons/code.var.sh
test/e2e/policies.test-suite/balloons/n4c32/test01-dynamic-baloons/multicontainerpod.yaml.in
test/e2e/policies.test-suite/balloons/n4c32/topology.var.json
test/e2e/policies.test-suite/balloons/verify.source.sh

This PR extends E2E to test idle CPU sharing (`ShareIdleCpusInSame` field)
and topology aware creation/inflation/deflation that is implemented in https://github.com/intel/cri-resource-manager/pull/931.

Balloons: add e2e tests for topology aware allocation and idle CPU sharing

---

pkg/cri/resource-manager/events.go
pkg/cri/resource-manager/policy/builtin/none/none-policy.go
pkg/cri/resource-manager/policy/flags.go
pkg/cri/resource-manager/policy/policy.go
pkg/cri/resource-manager/requests.go
pkg/cri/server/server.go
sample-configs/cri-full-message-dump.cfg
sample-configs/cri-kubelet-message-dump.cfg

Remove the 'null' pseudo-policy and the related bypass code-paths which leave part of the normal CRI relaying and intercepting infra uninitialized. Use the no-op `none` policy as the default. This setup should be a much more reasonable default. It should also allow us to change the handling of configuration updates to enable/handle the switch from the default `none` policy to any other one.

resource-manager: remove 'null' pseudo-policy.

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go

- Print first effective configuration. Allows debugging which configuration is used on policy start-up that affects reassignment of running workloads.
- Print CPU requests and limits of containers whose resources are to be allocated.
This PR is part of the series that replaces PR https://github.com/intel/cri-resource-manager/pull/931.

balloons: add debug logging

---

test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh

- This change relaxes balloon assignment checking by allowing containers to include non-test related containers such as cri-resmgr-webhook.
This PR is part of the series that replaces PR https://github.com/intel/cri-resource-manager/pull/931.

balloons: e2e allow other containers in the same balloons

---

pkg/cri/resource-manager/requests.go
pkg/cri/resource-manager/resource-manager.go

Until/unless Vertical Pod Autoscaling is fully implemented, receiving a CRI UpdateContainerResources request indicates that kubelet is running with the CPU Manager enabled and something else than the 'none' policy (typically 'static') active. This does not make sense when cri-resmgr is on the kubelet-runtime signalling path. Give a warning if / when the first such request is received.

resmgr: warn (once) about CRI update requests.

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
test/e2e/policies.test-suite/balloons/balloons-configmap.yaml.in
test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh

- When MaxCpus=NoLimit=0, maximum available CPUs of a balloon depends on the number of free CPUs in the system.
- Validate min/max values in balloons policy configurations.

balloons: fix handling of undefined (unlimited) MaxCPUs

---

pkg/cri/resource-manager/policy/builtin/balloons/cputree.go
pkg/cri/resource-manager/policy/builtin/balloons/cputree_test.go

These functions implement following features.
- Support topology aware resizing of allocated set of CPUs: from which set to allocate CPUs so that they are closest to already allocated CPUs, and release CPUs so that they are most separated from allocated CPUs.
- Report packages/dies/numas over which a cpuset spans over.
This PR is part of the series that replaces PR https://github.com/intel/cri-resource-manager/pull/931.

balloons: add CPU topology tree functions

---

Makefile
dockerfiles/cross-build/Dockerfile.fedora.in

Install glibc-static in the builder image that we use for building "binary-dist" tarball. Also changes the builder image of the "distroless" binary tarball to Fedora instead of the ancient CentOS that were used previously.

Makefile: fix cross-tar target

---

Makefile
dockerfiles/cross-build/Dockerfile.centos-7
dockerfiles/cross-build/Dockerfile.centos-8
dockerfiles/cross-build/Dockerfile.debian-10
dockerfiles/cross-build/Dockerfile.debian-sid
dockerfiles/cross-build/Dockerfile.fedora
dockerfiles/cross-build/Dockerfile.suse-15.4
dockerfiles/cross-build/Dockerfile.ubuntu-18.04
dockerfiles/cross-build/Dockerfile.ubuntu-20.04
dockerfiles/cross-build/Dockerfile.ubuntu-22.04
scripts/build/docker-build-image

Automatic detection of Golang version from go.mod does not work properly as with that we don't get the latest patch release, but the dot-zero version of it. It worked correctly for webhook and agent builds as the golang:maj.min docker images (that we use for building those) always point to the latest patch release but the rpm and deb builds were flawed.
The upside of this change is that we get more reproducible builds as the golang version is fixed. The downside is that we need to manually keep updating the version.

Makefile: specify go version in a make variable

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
pkg/cri/resource-manager/policy/builtin/balloons/flags.go

- Add AllocatorTopologyBalancing configuration option.
- Use cputree functions to restrict the number of CPUs from which the
CPU allocator selects which CPUs to allocate or release.
This PR depends on and includes commits from PR #941. 
This PR is part of the series that replaces PR #931.

balloons: topology aware balloon creation/inflation/deflation

---

.github/ISSUE_TEMPLATE/new-release.md

Instruct to use 'cross-tar' make target for building the "distroless" binary tarball. This builds inside a container (like cross targets) which means that we have more reproducible builds, e.g. using the golang version specified in the Makefile instead of using whatever happens to be installed on the host system (if any).

github: update release instructions

---

demo/lib/distro.bash
demo/lib/vm.bash

- Update govm opensuse to 15.4.
- Drop support from 15.3 that will be EOL'd in Dec 2022.
- Allow switching govm/Qemu VGA disabling depending on distro. OpenSUSE 15.4 fails to boot when Qemu VGA is disabled, but Ubuntu 22.04 guest VM has issues in qemu -vga QXL.
Enables passing opensuse-15.4 packaging tests in PR #952.

e2e: add opensuse-15.4, drop 15.3, DISABLE_VGA depends on distro

---

Makefile

Also build the "distroless" binary tarball with the corss-packages
target similar to the deb and rpm packages.
Also, change packaging-tests target to depend on cross-packages so that
it also tests the binary tarball. Even if it currently only tests the
buildability of the tarball as there is no actual e2e test to install
and verify it. Adding a packaging e2e-test for the binary tarball is
left as a future exercise.

Makefile: add cross-tar to cross-packages

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
pkg/cri/resource-manager/policy/builtin/balloons/flags.go

- Add ShareIdleCpusInSame: <topo-level> option to balloon types.
- Fix FillNewBalloon* fill methods to verify that new balloon can be
inflated to fit new container.
This PR depends on and includes commits from PR #945 and PR #942.
This PR is part of the series that replaces PR #931.

balloons: add topology aware idle CPU sharing to balloons

---

Makefile
dockerfiles/cross-build/Dockerfile.fedora

Build a dynamically linked cri-resmgr binary with the binary-dist target. Change the builder image from fedora to centos-7 in order to link against as-old-as possible glibc version to mitigate risk of users hitting glibc symbol version skew.
Also clean up fedora builder dockerfile to remove support for static linking.

Makefile: dynamically linked binary-dist

---

pkg/cri/resource-manager/policy/builtin/balloons/metrics.go
test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh

This PR depends on and includes commits from PR #946.
This PR is part of the series that replaces PR #931.

balloons: add sharedidlecpus and balloon topology to metrics

---

Makefile
cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile
dockerfiles/cross-build/Dockerfile.centos-7
dockerfiles/cross-build/Dockerfile.centos-8
dockerfiles/cross-build/Dockerfile.debian-10
dockerfiles/cross-build/Dockerfile.debian-sid
dockerfiles/cross-build/Dockerfile.fedora
dockerfiles/cross-build/Dockerfile.suse-15.4
dockerfiles/cross-build/Dockerfile.ubuntu-18.04
dockerfiles/cross-build/Dockerfile.ubuntu-20.04
dockerfiles/cross-build/Dockerfile.ubuntu-22.04
packaging/deb.in/rules
packaging/rpm/cri-resource-manager.spec.in
scripts/build/docker-build-image

Use the go-licenses tool to save all used licenses (plus MPL-licensed
code) inside all distributed binary "archives". That is deb and rpm
packages, the "distroless" binary tarball and the container images of
cri-resmgr-agent and cri-resmgr-webhook.
For agent and webhook dockerfiles this patch also adds the -x flag to go
mod download to print progress information.

packaging: store licenses

---

Makefile
packaging/deb.in/rules

Align with other packages i.e. rpm and the binary tarball.

packaging/: drop agent and webhook from deb packages

---

demo/lib/vm.bash

- Update weavenet installation URL.
- distro=centos-7 creates a working k8s cluster again.

e2e: fix k8scni=weavenet needed by distro=centos-7

---

test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion/code.var.sh

Linux kernel autonuma may cause flakiness in page demotion test.

e2e: disable numa_balancing in dynamic page demotion test

---

pkg/cgroups/cgroupcontrol.go
pkg/cgroups/cgrouppath.go

- Fixes page demotion in cgroup v2. This was failing because GetProcesses() and GetCgroupDir() did not work.

cgroups: fix controller filesystem path in cgroup v2

---

pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go

The policy must not miss containers that have been deleted when synchronizing its state at start.

balloons: fix synchronizing running containers at start

---

pkg/cri/resource-manager/policy/builtin/podpools/podpools-policy.go
test/e2e/policies.test-suite/podpools/n4c16/test06-prometheus-metrics/code.var.sh

This change makes podpools start similar to the balloons policy start: find all running containers in the system.

podpools: fix synchronizing all running containers at start

---

demo/lib/distro.bash

- Fixes topology-aware/n4c16/test08-isolcpus test on Fedora.

e2e: fix isolcpus test on Fedora

---

pkg/sysfs/system.go

This change enables policies to read and use cri-resmgr --host-root value, that will help validation and running in custom environments.

sysfs: add SysRoot() getter for SetSysRoot()

---

pkg/cpuallocator/allocator.go

The CPU priorities were discovered correctly but not stored in the cpuallocator so they were effectively discarded.

cpuallocator: fix cpu priority discovery

---

pkg/cri/resource-manager/control/rdt/rdt.go

We don't use that information for anything. In an error case we'll get the same error from container.GetProcesses() later anyway.

rdt: stop trying to get container cgroup dir

---

pkg/cgroups/cgroupstats.go

- Hugetlb statistics collector matched both usage and (later added) reservation accounting files (*.rsvd.*). When both were present, the collector tried to create duplicate metrics entries: usage and reservation values got the same name and labels.
- This patch ignores *.rsvd.* files when collecting statistics in order to keep reporting exactly what was reported before them.
- Fixes error "cgroup_hugetlb_usage... collected before with the same name and label values" error in cri-resmgr output.
- Fixes issue #859.

metrics: fix collecting hugetlb statistics from cgroup v1

---

pkg/cpuallocator/allocator.go

The CPU priorities were discovered correctly but not stored in the cpuallocator so they were effectively discarded.
(cherry picked from commit daa821d5bdd9bba6a2e3e810d06f2b79b1fb9604)
Backports #971

[release-0.8] cpuallocator: fix cpu priority discovery

---

.github/workflows/verify.yml
Makefile
cmd/cri-resmgr-agent/Dockerfile
cmd/cri-resmgr-webhook/Dockerfile
go.mod
pkg/apis/resmgr/generated/clientset/versioned/fake/register.go
pkg/apis/resmgr/generated/clientset/versioned/scheme/register.go
pkg/avx/collector.go
pkg/blockio/blockio_test.go
pkg/cgroups/cgroupblkio.go
pkg/cpuallocator/allocator.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/log/log.go

Bump from v1.18 to the latest patch release of v1.19. v1.18 has been archived so it's better not to use it anymore.

Bump builds to use Golang v1.19.6

---

pkg/avx/collector.go

Don't assume blindly that the regexp match in the  avx collector will produce a non-empty slice of results. Otherwise it might crash if we try to index an empty slice with `0`.

pkg/avx/collector: don't crash on no regexp match.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Fix logging changes to allowed and reserved cpuset when configuration is updated. The cpusets were logged the wrong way around.

topology-aware: fix logging of cpuset changes.

---

pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go

Cherry-picked #995/37f9c325 to release-0.8.

[release-0.8] topology-aware: fix logging of cpuset changes

---

pkg/cri/resource-manager/control/rdt/rdt.go

We don't use that information for anything. In an error case we'll get the same error from container.GetProcesses() later anyway.
(cherry picked from commit 61acbd7cbf7c93eab503fc8de479b9855f432ac3)

[release-0.8] rdt: stop trying to get container cgroup dir

---

.github/workflows/verify.yml

Fix the verify workflow to actually install the version of Go specified
in go.mod. Previously, because of the yaml parsing peculiarities go v1.2 was
installed.
Also changes the order of steps so that go.mod is available.
> **NOTE:** This expects that the practice from now on is to keep the Go version
> in go.mod and Makefile in sync.

github: take golang version from go.mod

---

Makefile
scripts/build/docker-build-image

The --container command like argument was skipped because of incorrect shift in the script which makes sure that it's really not used.

scripts: drop unused stuff from docker-build-image

---

docs/Dockerfile

Speeds up subsequent builds as the tarball will be cached.

docs: use ADD in the dockerfile to fetch go tarball

---

Makefile

When cross-building binary packages (rpm, deb, tarball), create a separate packages/release-assets directory where all binary packages are copied with a distintive distro-specific name. Make cutting releases way easier by removing the need for manual renaming (because without the distro-specific naming package names would clash). Also opens up the possibility to automatic uploading of release assets.

Makefile: prepare binary packages as release assets

---

dockerfiles/cross-build/Dockerfile.centos-7
dockerfiles/cross-build/Dockerfile.centos-8
dockerfiles/cross-build/Dockerfile.debian-10
dockerfiles/cross-build/Dockerfile.debian-sid
dockerfiles/cross-build/Dockerfile.fedora
dockerfiles/cross-build/Dockerfile.opensuse-leap-15.4
dockerfiles/cross-build/Dockerfile.ubuntu-18.04
dockerfiles/cross-build/Dockerfile.ubuntu-20.04
dockerfiles/cross-build/Dockerfile.ubuntu-22.04

Speed up builds considerably by reducing the download times (the golang tarball will be cached by docker) and skipping the build of golang itself.

cross-build: get golang binaries instead of compiling from source

---

.github/workflows/verify.yml
go.mod
go.sum
pkg/blockio/blockio.go
pkg/cgroups/cgroupblkio.go
pkg/cri/resource-manager/control/blockio/blockio.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/testutils/verify.go

Go v1.20 supports wrapping multiple errors into one.
Depends on #1022

Use golang builtin multierror

---

Makefile

This make target is basically just for CI. Decoupling image-push from image makes it easier to separate the image build and publish steps, without unnecessary extra runs of docker build.

Makefile: isolate image-push from image target

---

.github/workflows/verify.yml

Buildability of docs and gh-pages update are verified in the following steps anyway. Dropping the containerized build of docs speeds up CI.

github: drop containerized build of docs from verify workflow

---

.github/workflows/common-build-docs.yaml
.github/workflows/publish-docs.yml
.github/workflows/verify.yml

Refactor the docs-build into a re-usable job called from both the verify and publish workflows.

github: refactor docs building

---

pkg/cgroups/cgroupstats.go
pkg/cri/resource-manager/cache/container.go

Fix the following rather innocent two codeql alerts:
- cache: escape '.' in topology path regexp
- cgroupstats: node to int-sized integer (as opposed to int64) before casting to int

fixes: fix a few innocent codeql alert.

---

Makefile

Makes it possible to run dockerized targets in CI, for example.

Makefile: remove -it arg from docker run

---

Makefile

Missing curly brackets caused wrong (undefined) shell variable to be used.

Makefile: fix creation of deb release assets

---

.github/workflows/common-codeql.yaml
.github/workflows/common-trivy.yaml
.github/workflows/verify.yml

Split the security scanning workflow into separate parameterized jobs. This makes them re-usable for diiferent workflows, e.g. CI on PRs and image-publishing.
Also drop unneeded and broken parts from the CodeQL scanning job.

github: split security scanning into re-usable jobs

---

.github/workflows/common-verify.yaml
.github/workflows/verify-periodic.yaml
.github/workflows/verify-pr.yaml

Change the verify workflow to run on PRs only. Add concurrency rule so that in-progress runs for a PR are canceled if the PR is updated before their completion.
Add a nightly verify workflow that runs on the master branch every day at 2:30 UTC.

github: refactor verify workflow

---

.github/workflows/common-build-images.yaml
.github/workflows/publish-devel-images.yaml
.github/workflows/release.yaml

Add two new workflows, "Release" and "Publish devel images". The first one is intended for building and publishing all release artefacts - we now add only container images. The second one is for image-publishing only from the master branch.
The patch also adds a common re-usable image building job.

github: add workflows for image building

---

.github/workflows/release.yaml

Add release job for publishing binary packages and the vendored dist tarball in the release workflow.

github: build and upload release assets in release workflow

---

.github/workflows/common-build-images.yaml
.github/workflows/publish-devel-images.yaml
.github/workflows/release.yaml

Fix the usage of github environments in the container image building. Environment cannot be specifiec in the "caller" job of re-usable "on workflow_call" workflows.

github: fix the usage of github environments

---

test/e2e/policies.test-suite/static-pools/n4c16/test99-cleanup/code.var.sh
test/e2e/policies.test-suite/static-pools/static-pools-lib.source.sh

Without this patch static-pools test suite leaves webhook and cmk node taint behind which will cause next tests on the same vm fail.

e2e: clean up vm as the last step in the static-pools test suite

---

test/e2e/policies.test-suite/topology-aware/n4c16/test09-container-exit/code.var.sh

"sleep" in the latest busybox does not create a child process named "sleep". Change process matching from sleep to matching pod0c0 parent/child instead.

e2e: fix topology-aware/n4c16/test09-container-exit test

---

test/e2e/run.sh
test/e2e/run_tests.sh

Run tests in the latest Ubuntu LTS by default.

e2e: update default distro from Ubuntu 20.04 to 22.04

---

test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/topology-aware/c4pmem4/test04-dynamic-page-demotion/code.var.sh

Strict requirement makes the test flaky. Give two more rounds time for detecting first memory moves.

e2e: relax dynamic demotion first detection round requirement

---

demo/lib/distro.bash

Fedora 36 has been EOL'd. Plus, we build rpm packages targeting fedora:latest.

e2e: use Fedora 38 for the fedora test target

---

demo/lib/distro.bash
demo/lib/vm.bash

Bridge networking is stupid and simple and works perfectly in our one node cluster setup. More complicated CNI setup brings no value in terms of testing cri-resmgr. Using bridge speeds up tests considerably (by eliminating all clilium/weavenet download and initialization time) plus should virtually eliminate all test flakyness related to CNI plugin failures.

e2e: use bridge cni plugin by default

---

demo/lib/topology.py

Fetching allowed resources (needed by "verify" and "report allowed") caused test failures when a process found by pgrep got terminated before reading its /proc/pid/files. This change omits pids whose files could not be read without errors.

e2e: ignore terminated processes on fetching allowed resources

---

demo/lib/vm.bash

In some cases there seems to be a race that the node is in ready condition but pod creation still fails because of default service account (in the default namespace) is missing.

e2e: check default serviceaccount in cluster readiness check

---

Makefile

The e2e-runner script will print out all results. Plus, it will exit with an error code if any tests fail.

Makefile: simplify packaging tests

---

demo/lib/vm.bash
test/e2e/policies.test-suite/topology-aware/n4c16/test08-isolcpus/code.var.sh

Drop the vm-force-restart() function and just use vm-reboot() instead.
Improve the vm-reboot() to do a forced restart (via Qemu command) if the
normal reboot fails - something that the old vm-force-restart() tried to
do. However, the old vm-force-restart() was broken as we always
unconditionally forced a qemu system resstart independent of whether the
normal shutdown succeeded or not. This led to races in rare cases where
the qemu command was executed precisely when the container was in not
running state. Not to mention that this practice never resulted in
graceful restarts.
Tha patch increases the sleep after reboot command to 10 seconds to
match what vm-force-restart() had, apparently to avoid inadvertent ssh
logins to a shutting down system (before ssh daemon is killed and actual …

e2e: drop vm-force-restart()

---

test/e2e/policies.test-suite/topology-aware/c4pmem4/test03-coldstart-deprecated-syntax/bb-coldstart.yaml.in
test/e2e/policies.test-suite/topology-aware/c4pmem4/test03-coldstart-deprecated-syntax/code.var.sh
test/e2e/policies.test-suite/topology-aware/c4pmem4/test03-coldstart/bb-coldstart.yaml.in
test/e2e/policies.test-suite/topology-aware/c4pmem4/test03-coldstart/code.var.sh

Increase the amount of memory allocated by the test container, in an attempt to reduce test flakyness by reducing the relative effect of "memory usage noise" caused by other system processes. Make the error threshold (acceptable marging of error) of coldstart memory allocation proportional, being 10 percent of the allocated size.
Also increase the wait duration of coldstart test to avoid flakyness on slow/heavily loaded systems.

e2e: relax topology-aware coldstart test

---

demo/lib/vm.bash

This patch generates new default containerd configuration file when a locally built containerd is installed from containerd_src. This fixes the problem where containerd configuration provided by the Linux distribution does not work with the containerd build defined by the user.

e2e: fix starting a custom containerd version

---

test/e2e/policies.test-suite/balloons/balloons-configmap.yaml.in
test/e2e/policies.test-suite/balloons/cri-resmgr.cfg
test/e2e/policies.test-suite/balloons/n4c16/test08-numa/balloons-numa.cfg
test/e2e/policies.test-suite/dynamic-pools/dyp-configmap.yaml.in

Fix incorrect config key in some balloons tests. Use more consistent test environment variables wrt. the actual config key.

test/e2e: fix incorrect Allocat[ion|or]Priority config key.

---

pkg/cpuallocator/cpuallocator_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/sysfs/system.go

Simplify the code by dropping unused functionality. Effectively, we always used the default flags.
Depends on #1082

pkg/sysfs: drop discovery flags

---

pkg/cri/relay/relay.go
pkg/cri/relay/runtime-service.go
pkg/cri/server/services.go

This PR implements relaying the stream of events for CRI streaming GetContainerEvents() calls.

pkg/cri: implement container event relaying.

---

.github/workflows/common-codeql.yaml
.github/workflows/common-verify-code.yaml

Silencing the last warnings from actions' logs (for now).

github: update setup-go action to v5

---

go.mod
go.sum
pkg/topology/go.mod

- bump google.golang.org/protobuf from 1.32.0 to 1.33.0
- bump golang.org/x/net from 0.19.0 to 0.23.0

[release-0.9] backport deps updates

---

go.mod
pkg/topology/go.mod

In Go v1.21 and later the patch version should be included (1.x.y syntax).

go.mod: use correct go toolchain version syntax

---

Makefile

Makefile: don't try to use centos builder image

---

demo/lib/vm.bash

Prevent "restart bomb" that causes systemd to throttle (re-)starting of cri-rm, that in turn, may cause following steps to fail.

e2e: create empty fallback config before installing the package

---

demo/lib/distro.bash
demo/lib/host.bash

Set DISABLE_VGA to false, otherwise the latest SID image fails to boot. Install gpg which is needed by apt-key add (but somehow missing from the system).  Also accept exit code 2 from cloud-init:
2 - Recoverable error - Cloud-init completed but experienced errors.

e2e: fixes to debian-sid

---

.github/workflows/verify-pr-code.yaml

Required by the branch-protection rules or something...

github: remove paths-ignore from verify-code

---

docs/developers-guide/e2e-test.md

We're not compatible with the latest govm.

docs: update the govm setup instructions

---

docs/conf.py

Should prevent docs build failures like:
SECURITY.md:document isn't included in any toctree

docs: exclude SECURITY.md from docs build

---

demo/lib/distro.bash

Need to apply hack after containerd config step, not after containerd install.

e2e: fix containerd config hack for debian-sid
